# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.6
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.models.player_public import PlayerPublic

class TestPlayerPublic(unittest.TestCase):
    """PlayerPublic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlayerPublic:
        """Test PlayerPublic
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlayerPublic`
        """
        model = PlayerPublic()
        if include_optional:
            return PlayerPublic(
                api_id = 56,
                eh_id = '',
                name = '',
                position = '',
                shoots = '',
                catches = '',
                birth_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                birth_city = '',
                birth_state_province = '',
                birth_country = '',
                nationality = '',
                height = 1.337,
                weight = 56
            )
        else:
            return PlayerPublic(
                api_id = 56,
                name = '',
        )
        """

    def testPlayerPublic(self):
        """Test PlayerPublic"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
