# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.6
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.api.inference_api import InferenceApi


class TestInferenceApi(unittest.TestCase):
    """InferenceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InferenceApi()

    def tearDown(self) -> None:
        pass

    def test_read_pred_goal(self) -> None:
        """Test case for read_pred_goal

        Read Pred Goal
        """
        pass


if __name__ == '__main__':
    unittest.main()
