# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.6
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.models.refresh_token_request import RefreshTokenRequest

class TestRefreshTokenRequest(unittest.TestCase):
    """RefreshTokenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RefreshTokenRequest:
        """Test RefreshTokenRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RefreshTokenRequest`
        """
        model = RefreshTokenRequest()
        if include_optional:
            return RefreshTokenRequest(
                refresh_token = ''
            )
        else:
            return RefreshTokenRequest(
                refresh_token = '',
        )
        """

    def testRefreshTokenRequest(self):
        """Test RefreshTokenRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
