# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.5
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.models.roster_public import RosterPublic

class TestRosterPublic(unittest.TestCase):
    """RosterPublic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RosterPublic:
        """Test RosterPublic
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RosterPublic`
        """
        model = RosterPublic()
        if include_optional:
            return RosterPublic(
                game_id = 56,
                api_id = 56,
                team = '',
                jersey = 56,
                position = '',
                starter = 56,
                rookie = 56,
                captain = 56,
                alternate_captain = 56,
                status = '',
                active = 56,
                player = chickenstats_api.models.player_public.PlayerPublic(
                    api_id = 56, 
                    eh_id = '', 
                    name = '', 
                    position = '', 
                    shoots = '', 
                    catches = '', 
                    birth_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    birth_city = '', 
                    birth_state_province = '', 
                    birth_country = '', 
                    nationality = '', 
                    height = 1.337, 
                    weight = 56, ),
                game = chickenstats_api.models.game_public.GamePublic(
                    game_id = 56, 
                    season = 56, 
                    session = '', 
                    game_date = '', 
                    start_time = '', 
                    start_time_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    game_state = '', 
                    game_schedule_state = '', 
                    game_outcome = '', 
                    home_team = '', 
                    away_team = '', 
                    home_score = 56, 
                    away_score = 56, 
                    venue = '', 
                    venue_location = '', 
                    venue_timezone = '', 
                    neutral_site = 56, )
            )
        else:
            return RosterPublic(
                game_id = 56,
                team = '',
        )
        """

    def testRosterPublic(self):
        """Test RosterPublic"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
