# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.4
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.api.login_api import LoginApi


class TestLoginApi(unittest.TestCase):
    """LoginApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LoginApi()

    def tearDown(self) -> None:
        pass

    def test_login_auth0_token(self) -> None:
        """Test case for login_auth0_token

        Login Auth0 Token
        """
        pass

    def test_login_callback(self) -> None:
        """Test case for login_callback

        Login Callback
        """
        pass

    def test_recover_password(self) -> None:
        """Test case for recover_password

        Recover Password
        """
        pass

    def test_recover_password_html_content(self) -> None:
        """Test case for recover_password_html_content

        Recover Password Html Content
        """
        pass

    def test_reset_password(self) -> None:
        """Test case for reset_password

        Reset Password
        """
        pass

    def test_test_token(self) -> None:
        """Test case for test_token

        Test Token
        """
        pass


if __name__ == '__main__':
    unittest.main()
