# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.6
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.api.standings_api import StandingsApi


class TestStandingsApi(unittest.TestCase):
    """StandingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StandingsApi()

    def tearDown(self) -> None:
        pass

    def test_read_standings(self) -> None:
        """Test case for read_standings

        Read Standings
        """
        pass


if __name__ == '__main__':
    unittest.main()
