# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.7
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_delete_user_me(self) -> None:
        """Test case for delete_user_me

        Delete User Me
        """
        pass

    def test_get_programmatic_credentials(self) -> None:
        """Test case for get_programmatic_credentials

        Get Programmatic Credentials
        """
        pass

    def test_read_user_me(self) -> None:
        """Test case for read_user_me

        Read User Me
        """
        pass

    def test_resend_verification(self) -> None:
        """Test case for resend_verification

        Resend Verification
        """
        pass

    def test_rotate_programmatic_credentials(self) -> None:
        """Test case for rotate_programmatic_credentials

        Rotate Programmatic Credentials
        """
        pass

    def test_signup(self) -> None:
        """Test case for signup

        Signup
        """
        pass

    def test_update_password_me(self) -> None:
        """Test case for update_password_me

        Update Password Me
        """
        pass

    def test_update_user_me(self) -> None:
        """Test case for update_user_me

        Update User Me
        """
        pass


if __name__ == '__main__':
    unittest.main()
