# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.7
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.models.changes_response import ChangesResponse

class TestChangesResponse(unittest.TestCase):
    """ChangesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChangesResponse:
        """Test ChangesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChangesResponse`
        """
        model = ChangesResponse()
        if include_optional:
            return ChangesResponse(
                count = 56,
                total = 56,
                limit = 56,
                offset = 56,
                has_next = True,
                data = [
                    chickenstats_api.models.changes_public.ChangesPublic(
                        season = 56, 
                        session = '', 
                        game_id = 56, 
                        event_team = '', 
                        event = '', 
                        event_type = '', 
                        description = '', 
                        period = 56, 
                        period_seconds = 56, 
                        game_seconds = 56, 
                        change_on_count = 56, 
                        change_off_count = 56, 
                        change_on_api_id = '', 
                        change_off_api_id = '', 
                        change_on_forwards_count = 56, 
                        change_off_forwards_count = 56, 
                        change_on_forwards_api_id = '', 
                        change_off_forwards_api_id = '', 
                        change_on_defense_count = 56, 
                        change_off_defense_count = 56, 
                        change_on_defense_api_id = '', 
                        change_off_defense_api_id = '', 
                        change_on_goalie_count = 56, 
                        change_off_goalie_count = 56, 
                        change_on_goalie_api_id = '', 
                        change_off_goalie_api_id = '', 
                        is_home = 56, 
                        game = chickenstats_api.models.game_public.GamePublic(
                            game_id = 56, 
                            season = 56, 
                            session = '', 
                            game_date = '', 
                            start_time = '', 
                            start_time_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            game_state = '', 
                            game_schedule_state = '', 
                            game_outcome = '', 
                            home_team = '', 
                            away_team = '', 
                            home_score = 56, 
                            away_score = 56, 
                            venue = '', 
                            venue_location = '', 
                            venue_timezone = '', 
                            neutral_site = 56, ), )
                    ]
            )
        else:
            return ChangesResponse(
                count = 56,
                total = 56,
                limit = 56,
                offset = 56,
                has_next = True,
                data = [
                    chickenstats_api.models.changes_public.ChangesPublic(
                        season = 56, 
                        session = '', 
                        game_id = 56, 
                        event_team = '', 
                        event = '', 
                        event_type = '', 
                        description = '', 
                        period = 56, 
                        period_seconds = 56, 
                        game_seconds = 56, 
                        change_on_count = 56, 
                        change_off_count = 56, 
                        change_on_api_id = '', 
                        change_off_api_id = '', 
                        change_on_forwards_count = 56, 
                        change_off_forwards_count = 56, 
                        change_on_forwards_api_id = '', 
                        change_off_forwards_api_id = '', 
                        change_on_defense_count = 56, 
                        change_off_defense_count = 56, 
                        change_on_defense_api_id = '', 
                        change_off_defense_api_id = '', 
                        change_on_goalie_count = 56, 
                        change_off_goalie_count = 56, 
                        change_on_goalie_api_id = '', 
                        change_off_goalie_api_id = '', 
                        is_home = 56, 
                        game = chickenstats_api.models.game_public.GamePublic(
                            game_id = 56, 
                            season = 56, 
                            session = '', 
                            game_date = '', 
                            start_time = '', 
                            start_time_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            game_state = '', 
                            game_schedule_state = '', 
                            game_outcome = '', 
                            home_team = '', 
                            away_team = '', 
                            home_score = 56, 
                            away_score = 56, 
                            venue = '', 
                            venue_location = '', 
                            venue_timezone = '', 
                            neutral_site = 56, ), )
                    ],
        )
        """

    def testChangesResponse(self):
        """Test ChangesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
