# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.5
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.api.lines_api import LinesApi


class TestLinesApi(unittest.TestCase):
    """LinesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LinesApi()

    def tearDown(self) -> None:
        pass

    def test_read_game_lines(self) -> None:
        """Test case for read_game_lines

        Read Game Lines
        """
        pass

    def test_read_lines_game_ids(self) -> None:
        """Test case for read_lines_game_ids

        Read Lines Game Ids
        """
        pass

    def test_read_lines_line_ids(self) -> None:
        """Test case for read_lines_line_ids

        Read Lines Line Ids
        """
        pass

    def test_read_season_lines(self) -> None:
        """Test case for read_season_lines

        Read Season Lines
        """
        pass


if __name__ == '__main__':
    unittest.main()
