# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.5
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.models.standings_response import StandingsResponse

class TestStandingsResponse(unittest.TestCase):
    """StandingsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StandingsResponse:
        """Test StandingsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StandingsResponse`
        """
        model = StandingsResponse()
        if include_optional:
            return StandingsResponse(
                count = 56,
                total = 56,
                limit = 56,
                offset = 56,
                has_next = True,
                data = [
                    chickenstats_api.models.standings_public.StandingsPublic(
                        season = 56, 
                        team = '', 
                        division_rank = 56, 
                        conference_rank = 56, 
                        league_rank = 56, 
                        division_rank_home = 56, 
                        division_rank_road = 56, 
                        division_rank_last10 = 56, 
                        conference_rank_home = 56, 
                        conference_rank_road = 56, 
                        conference_rank_last10 = 56, 
                        league_rank_home = 56, 
                        league_rank_road = 56, 
                        league_rank_last10 = 56, 
                        wildcard_rank = 56, 
                        points = 56, 
                        points_percentage = 1.337, 
                        wins = 56, 
                        losses = 56, 
                        otl = 56, 
                        games_played = 56, 
                        goals_scored = 56, 
                        goals_against = 56, 
                        streak = '', 
                        pp_rank_division = 56, 
                        pp_rank_conference = 56, 
                        pp_rank_league = 56, 
                        last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return StandingsResponse(
                count = 56,
                total = 56,
                limit = 56,
                offset = 56,
                has_next = True,
                data = [
                    chickenstats_api.models.standings_public.StandingsPublic(
                        season = 56, 
                        team = '', 
                        division_rank = 56, 
                        conference_rank = 56, 
                        league_rank = 56, 
                        division_rank_home = 56, 
                        division_rank_road = 56, 
                        division_rank_last10 = 56, 
                        conference_rank_home = 56, 
                        conference_rank_road = 56, 
                        conference_rank_last10 = 56, 
                        league_rank_home = 56, 
                        league_rank_road = 56, 
                        league_rank_last10 = 56, 
                        wildcard_rank = 56, 
                        points = 56, 
                        points_percentage = 1.337, 
                        wins = 56, 
                        losses = 56, 
                        otl = 56, 
                        games_played = 56, 
                        goals_scored = 56, 
                        goals_against = 56, 
                        streak = '', 
                        pp_rank_division = 56, 
                        pp_rank_conference = 56, 
                        pp_rank_league = 56, 
                        last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
        )
        """

    def testStandingsResponse(self):
        """Test StandingsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
