# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.5
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.models.team_public import TeamPublic

class TestTeamPublic(unittest.TestCase):
    """TeamPublic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamPublic:
        """Test TeamPublic
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamPublic`
        """
        model = TeamPublic()
        if include_optional:
            return TeamPublic(
                code = '',
                team_name = '',
                team_id = 56,
                division = '',
                division_id = 56,
                conference = '',
                conference_id = 56
            )
        else:
            return TeamPublic(
                code = '',
        )
        """

    def testTeamPublic(self):
        """Test TeamPublic"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
