# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.6
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.api.shifts_api import ShiftsApi


class TestShiftsApi(unittest.TestCase):
    """ShiftsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ShiftsApi()

    def tearDown(self) -> None:
        pass

    def test_read_shifts(self) -> None:
        """Test case for read_shifts

        Read Shifts
        """
        pass

    def test_read_shifts_game_ids(self) -> None:
        """Test case for read_shifts_game_ids

        Read Shifts Game Ids
        """
        pass


if __name__ == '__main__':
    unittest.main()
