# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.4
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.models.live_games_public import LiveGamesPublic

class TestLiveGamesPublic(unittest.TestCase):
    """LiveGamesPublic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LiveGamesPublic:
        """Test LiveGamesPublic
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LiveGamesPublic`
        """
        model = LiveGamesPublic()
        if include_optional:
            return LiveGamesPublic(
                game_id = 56,
                game_date = '',
                home_team = '',
                away_team = '',
                game_state = '',
                period = 56,
                time_remaining = '',
                home_score = 56,
                away_score = 56,
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return LiveGamesPublic(
                game_id = 56,
                game_date = '',
                home_team = '',
                away_team = '',
                game_state = '',
                period = 56,
                time_remaining = '',
                home_score = 56,
                away_score = 56,
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testLiveGamesPublic(self):
        """Test LiveGamesPublic"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
