# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.5
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.api.rosters_api import RostersApi


class TestRostersApi(unittest.TestCase):
    """RostersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RostersApi()

    def tearDown(self) -> None:
        pass

    def test_read_roster_game_ids(self) -> None:
        """Test case for read_roster_game_ids

        Read Roster Game Ids
        """
        pass

    def test_read_rosters(self) -> None:
        """Test case for read_rosters

        Read Rosters
        """
        pass


if __name__ == '__main__':
    unittest.main()
