# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.4
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.api.rapm_api import RapmApi


class TestRapmApi(unittest.TestCase):
    """RapmApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RapmApi()

    def tearDown(self) -> None:
        pass

    def test_read_rapm(self) -> None:
        """Test case for read_rapm

        Read Rapm
        """
        pass


if __name__ == '__main__':
    unittest.main()
