# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.5
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.models.programmatic_credentials import ProgrammaticCredentials

class TestProgrammaticCredentials(unittest.TestCase):
    """ProgrammaticCredentials unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProgrammaticCredentials:
        """Test ProgrammaticCredentials
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProgrammaticCredentials`
        """
        model = ProgrammaticCredentials()
        if include_optional:
            return ProgrammaticCredentials(
                cf_client_id = '',
                cf_client_secret = '',
                token_endpoint = 'POST /api/v1/login/firebase-token',
                note = 'The secret is shown once. Store it securely — rotate if lost.'
            )
        else:
            return ProgrammaticCredentials(
                cf_client_id = '',
        )
        """

    def testProgrammaticCredentials(self):
        """Test ProgrammaticCredentials"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
