# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.4
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.api.live_api import LiveApi


class TestLiveApi(unittest.TestCase):
    """LiveApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LiveApi()

    def tearDown(self) -> None:
        pass

    def test_read_live_games(self) -> None:
        """Test case for read_live_games

        Read Live Games
        """
        pass

    def test_read_live_pbp(self) -> None:
        """Test case for read_live_pbp

        Read Live Pbp
        """
        pass


if __name__ == '__main__':
    unittest.main()
