# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.5
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.api.billing_api import BillingApi


class TestBillingApi(unittest.TestCase):
    """BillingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BillingApi()

    def tearDown(self) -> None:
        pass

    def test_create_checkout_session(self) -> None:
        """Test case for create_checkout_session

        Create Checkout Session
        """
        pass

    def test_create_portal_session(self) -> None:
        """Test case for create_portal_session

        Create Portal Session
        """
        pass


if __name__ == '__main__':
    unittest.main()
