# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.6
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.api.changes_api import ChangesApi


class TestChangesApi(unittest.TestCase):
    """ChangesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChangesApi()

    def tearDown(self) -> None:
        pass

    def test_read_changes(self) -> None:
        """Test case for read_changes

        Read Changes
        """
        pass

    def test_read_changes_game_ids(self) -> None:
        """Test case for read_changes_game_ids

        Read Changes Game Ids
        """
        pass


if __name__ == '__main__':
    unittest.main()
