# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.7
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.api.team_stats_api import TeamStatsApi


class TestTeamStatsApi(unittest.TestCase):
    """TeamStatsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TeamStatsApi()

    def tearDown(self) -> None:
        pass

    def test_read_game_team_stats(self) -> None:
        """Test case for read_game_team_stats

        Read Game Team Stats
        """
        pass

    def test_read_season_team_stats(self) -> None:
        """Test case for read_season_team_stats

        Read Season Team Stats
        """
        pass

    def test_read_team_stats_game_ids(self) -> None:
        """Test case for read_team_stats_game_ids

        Read Team Stats Game Ids
        """
        pass

    def test_read_team_stats_ids(self) -> None:
        """Test case for read_team_stats_ids

        Read Team Stats Ids
        """
        pass


if __name__ == '__main__':
    unittest.main()
