# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.5
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.models.team_stats_public import TeamStatsPublic

class TestTeamStatsPublic(unittest.TestCase):
    """TeamStatsPublic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamStatsPublic:
        """Test TeamStatsPublic
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamStatsPublic`
        """
        model = TeamStatsPublic()
        if include_optional:
            return TeamStatsPublic(
                toi = 1.337,
                gf = 56,
                ga = 56,
                gf_adj = 1.337,
                ga_adj = 1.337,
                hdgf = 56,
                hdga = 56,
                base_xgf = 1.337,
                base_xga = 1.337,
                base_xgf_adj = 1.337,
                base_xga_adj = 1.337,
                context_xgf = 1.337,
                context_xga = 1.337,
                context_xgf_adj = 1.337,
                context_xga_adj = 1.337,
                xgf = 1.337,
                xga = 1.337,
                xgf_adj = 1.337,
                xga_adj = 1.337,
                sf = 56,
                sa = 56,
                sf_adj = 1.337,
                sa_adj = 1.337,
                hdsf = 56,
                hdsa = 56,
                ff = 56,
                fa = 56,
                ff_adj = 1.337,
                fa_adj = 1.337,
                hdff = 56,
                hdfa = 56,
                cf = 56,
                ca = 56,
                cf_adj = 1.337,
                ca_adj = 1.337,
                bsf = 56,
                bsa = 56,
                bsf_adj = 1.337,
                bsa_adj = 1.337,
                msf = 56,
                msa = 56,
                msf_adj = 1.337,
                msa_adj = 1.337,
                hdmsf = 56,
                hdmsa = 56,
                teammate_block = 56,
                teammate_block_adj = 1.337,
                hf = 56,
                ht = 56,
                ozf = 56,
                nzf = 56,
                dzf = 56,
                fow = 56,
                fol = 56,
                ozfw = 56,
                ozfl = 56,
                nzfw = 56,
                nzfl = 56,
                dzfw = 56,
                dzfl = 56,
                pent0 = 56,
                pent2 = 56,
                pent4 = 56,
                pent5 = 56,
                pent10 = 56,
                pend0 = 56,
                pend2 = 56,
                pend4 = 56,
                pend5 = 56,
                pend10 = 56,
                season = 56,
                session = '',
                game_id = 56,
                team = '',
                opp_team = '',
                strength_state = '',
                period = 56,
                score_state = ''
            )
        else:
            return TeamStatsPublic(
                toi = 1.337,
                season = 56,
                session = '',
                game_id = 56,
                team = '',
        )
        """

    def testTeamStatsPublic(self):
        """Test TeamStatsPublic"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
