# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.7
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from chickenstats_api.api.games_api import GamesApi


class TestGamesApi(unittest.TestCase):
    """GamesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GamesApi()

    def tearDown(self) -> None:
        pass

    def test_read_game(self) -> None:
        """Test case for read_game

        Read Game
        """
        pass

    def test_read_games(self) -> None:
        """Test case for read_games

        Read Games
        """
        pass


if __name__ == '__main__':
    unittest.main()
