# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.4
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr
from typing import List, Optional
from typing_extensions import Annotated
from chickenstats_api.models.pred_goal_response import PredGoalResponse

from chickenstats_api.api_client import ApiClient, RequestSerialized
from chickenstats_api.api_response import ApiResponse
from chickenstats_api.rest import RESTResponseType


class InferenceApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def read_pred_goal(
        self,
        game_id: Optional[List[StrictInt]] = None,
        season: Optional[List[StrictInt]] = None,
        sessions: Optional[List[StrictStr]] = None,
        limit: Optional[Annotated[int, Field(le=100000, strict=True, ge=1)]] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> PredGoalResponse:
        """Read Pred Goal

        Pre-computed pred_goal values from pbpcs for shot/miss/goal events.

        :param game_id:
        :type game_id: List[int]
        :param season:
        :type season: List[int]
        :param sessions:
        :type sessions: List[str]
        :param limit:
        :type limit: int
        :param offset:
        :type offset: int
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_pred_goal_serialize(
            game_id=game_id,
            season=season,
            sessions=sessions,
            limit=limit,
            offset=offset,
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PredGoalResponse",
            '422': "HTTPValidationError",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def read_pred_goal_with_http_info(
        self,
        game_id: Optional[List[StrictInt]] = None,
        season: Optional[List[StrictInt]] = None,
        sessions: Optional[List[StrictStr]] = None,
        limit: Optional[Annotated[int, Field(le=100000, strict=True, ge=1)]] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> ApiResponse[PredGoalResponse]:
        """Read Pred Goal

        Pre-computed pred_goal values from pbpcs for shot/miss/goal events.

        :param game_id:
        :type game_id: List[int]
        :param season:
        :type season: List[int]
        :param sessions:
        :type sessions: List[str]
        :param limit:
        :type limit: int
        :param offset:
        :type offset: int
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_pred_goal_serialize(
            game_id=game_id,
            season=season,
            sessions=sessions,
            limit=limit,
            offset=offset,
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PredGoalResponse",
            '422': "HTTPValidationError",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def read_pred_goal_without_preload_content(
        self,
        game_id: Optional[List[StrictInt]] = None,
        season: Optional[List[StrictInt]] = None,
        sessions: Optional[List[StrictStr]] = None,
        limit: Optional[Annotated[int, Field(le=100000, strict=True, ge=1)]] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> RESTResponseType:
        """Read Pred Goal

        Pre-computed pred_goal values from pbpcs for shot/miss/goal events.

        :param game_id:
        :type game_id: List[int]
        :param season:
        :type season: List[int]
        :param sessions:
        :type sessions: List[str]
        :param limit:
        :type limit: int
        :param offset:
        :type offset: int
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_pred_goal_serialize(
            game_id=game_id,
            season=season,
            sessions=sessions,
            limit=limit,
            offset=offset,
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PredGoalResponse",
            '422': "HTTPValidationError",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _read_pred_goal_serialize(
        self,
        game_id,
        season,
        sessions,
        limit,
        offset,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'game_id': 'multi',
            'season': 'multi',
            'sessions': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if game_id is not None:
            
            _query_params.append(('game_id', game_id))
            
        if season is not None:
            
            _query_params.append(('season', season))
            
        if sessions is not None:
            
            _query_params.append(('sessions', sessions))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'OAuth2PasswordBearer'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/inference/pred_goal',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


