# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.6
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt
from typing import List, Optional
from typing_extensions import Annotated
from chickenstats_api.models.live_games_public import LiveGamesPublic
from chickenstats_api.models.live_pbp_response import LivePbpResponse

from chickenstats_api.api_client import ApiClient, RequestSerialized
from chickenstats_api.api_response import ApiResponse
from chickenstats_api.rest import RESTResponseType


class LiveApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def read_live_games(
        self,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> List[LiveGamesPublic]:
        """Read Live Games


        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_live_games_serialize(
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[LiveGamesPublic]",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def read_live_games_with_http_info(
        self,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> ApiResponse[List[LiveGamesPublic]]:
        """Read Live Games


        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_live_games_serialize(
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[LiveGamesPublic]",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def read_live_games_without_preload_content(
        self,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> RESTResponseType:
        """Read Live Games


        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_live_games_serialize(
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[LiveGamesPublic]",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _read_live_games_serialize(
        self,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'OAuth2PasswordBearer'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/live/games',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def read_live_pbp(
        self,
        game_id: Optional[List[StrictInt]] = None,
        limit: Optional[Annotated[int, Field(le=50000, strict=True, ge=1)]] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> LivePbpResponse:
        """Read Live Pbp


        :param game_id:
        :type game_id: List[int]
        :param limit:
        :type limit: int
        :param offset:
        :type offset: int
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_live_pbp_serialize(
            game_id=game_id,
            limit=limit,
            offset=offset,
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "LivePbpResponse",
            '422': "HTTPValidationError",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def read_live_pbp_with_http_info(
        self,
        game_id: Optional[List[StrictInt]] = None,
        limit: Optional[Annotated[int, Field(le=50000, strict=True, ge=1)]] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> ApiResponse[LivePbpResponse]:
        """Read Live Pbp


        :param game_id:
        :type game_id: List[int]
        :param limit:
        :type limit: int
        :param offset:
        :type offset: int
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_live_pbp_serialize(
            game_id=game_id,
            limit=limit,
            offset=offset,
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "LivePbpResponse",
            '422': "HTTPValidationError",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def read_live_pbp_without_preload_content(
        self,
        game_id: Optional[List[StrictInt]] = None,
        limit: Optional[Annotated[int, Field(le=50000, strict=True, ge=1)]] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> RESTResponseType:
        """Read Live Pbp


        :param game_id:
        :type game_id: List[int]
        :param limit:
        :type limit: int
        :param offset:
        :type offset: int
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_live_pbp_serialize(
            game_id=game_id,
            limit=limit,
            offset=offset,
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "LivePbpResponse",
            '422': "HTTPValidationError",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _read_live_pbp_serialize(
        self,
        game_id,
        limit,
        offset,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'game_id': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if game_id is not None:
            
            _query_params.append(('game_id', game_id))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'OAuth2PasswordBearer'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/live/play_by_play',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


