# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.6
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr, field_validator
from typing import List, Optional
from typing_extensions import Annotated
from chickenstats_api.models.pbp_response import PbpResponse

from chickenstats_api.api_client import ApiClient, RequestSerialized
from chickenstats_api.api_response import ApiResponse
from chickenstats_api.rest import RESTResponseType


class PlayByPlayApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def read_pbp(
        self,
        season: Optional[List[StrictInt]] = None,
        sessions: Optional[List[StrictStr]] = None,
        game_id: Optional[List[StrictInt]] = None,
        play_id: Optional[List[StrictInt]] = None,
        event: Optional[List[StrictStr]] = None,
        player_1: Optional[List[StrictStr]] = None,
        goalie: Optional[List[StrictStr]] = None,
        event_team: Optional[List[StrictStr]] = None,
        opp_team: Optional[List[StrictStr]] = None,
        strength_state: Optional[List[StrictStr]] = None,
        include: Optional[List[StrictStr]] = None,
        limit: Optional[Annotated[int, Field(le=50000, strict=True, ge=1)]] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> PbpResponse:
        """Read Pbp


        :param season:
        :type season: List[int]
        :param sessions:
        :type sessions: List[str]
        :param game_id:
        :type game_id: List[int]
        :param play_id:
        :type play_id: List[int]
        :param event:
        :type event: List[str]
        :param player_1:
        :type player_1: List[str]
        :param goalie:
        :type goalie: List[str]
        :param event_team:
        :type event_team: List[str]
        :param opp_team:
        :type opp_team: List[str]
        :param strength_state:
        :type strength_state: List[str]
        :param include:
        :type include: List[str]
        :param limit:
        :type limit: int
        :param offset:
        :type offset: int
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_pbp_serialize(
            season=season,
            sessions=sessions,
            game_id=game_id,
            play_id=play_id,
            event=event,
            player_1=player_1,
            goalie=goalie,
            event_team=event_team,
            opp_team=opp_team,
            strength_state=strength_state,
            include=include,
            limit=limit,
            offset=offset,
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PbpResponse",
            '422': "HTTPValidationError",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def read_pbp_with_http_info(
        self,
        season: Optional[List[StrictInt]] = None,
        sessions: Optional[List[StrictStr]] = None,
        game_id: Optional[List[StrictInt]] = None,
        play_id: Optional[List[StrictInt]] = None,
        event: Optional[List[StrictStr]] = None,
        player_1: Optional[List[StrictStr]] = None,
        goalie: Optional[List[StrictStr]] = None,
        event_team: Optional[List[StrictStr]] = None,
        opp_team: Optional[List[StrictStr]] = None,
        strength_state: Optional[List[StrictStr]] = None,
        include: Optional[List[StrictStr]] = None,
        limit: Optional[Annotated[int, Field(le=50000, strict=True, ge=1)]] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> ApiResponse[PbpResponse]:
        """Read Pbp


        :param season:
        :type season: List[int]
        :param sessions:
        :type sessions: List[str]
        :param game_id:
        :type game_id: List[int]
        :param play_id:
        :type play_id: List[int]
        :param event:
        :type event: List[str]
        :param player_1:
        :type player_1: List[str]
        :param goalie:
        :type goalie: List[str]
        :param event_team:
        :type event_team: List[str]
        :param opp_team:
        :type opp_team: List[str]
        :param strength_state:
        :type strength_state: List[str]
        :param include:
        :type include: List[str]
        :param limit:
        :type limit: int
        :param offset:
        :type offset: int
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_pbp_serialize(
            season=season,
            sessions=sessions,
            game_id=game_id,
            play_id=play_id,
            event=event,
            player_1=player_1,
            goalie=goalie,
            event_team=event_team,
            opp_team=opp_team,
            strength_state=strength_state,
            include=include,
            limit=limit,
            offset=offset,
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PbpResponse",
            '422': "HTTPValidationError",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def read_pbp_without_preload_content(
        self,
        season: Optional[List[StrictInt]] = None,
        sessions: Optional[List[StrictStr]] = None,
        game_id: Optional[List[StrictInt]] = None,
        play_id: Optional[List[StrictInt]] = None,
        event: Optional[List[StrictStr]] = None,
        player_1: Optional[List[StrictStr]] = None,
        goalie: Optional[List[StrictStr]] = None,
        event_team: Optional[List[StrictStr]] = None,
        opp_team: Optional[List[StrictStr]] = None,
        strength_state: Optional[List[StrictStr]] = None,
        include: Optional[List[StrictStr]] = None,
        limit: Optional[Annotated[int, Field(le=50000, strict=True, ge=1)]] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> RESTResponseType:
        """Read Pbp


        :param season:
        :type season: List[int]
        :param sessions:
        :type sessions: List[str]
        :param game_id:
        :type game_id: List[int]
        :param play_id:
        :type play_id: List[int]
        :param event:
        :type event: List[str]
        :param player_1:
        :type player_1: List[str]
        :param goalie:
        :type goalie: List[str]
        :param event_team:
        :type event_team: List[str]
        :param opp_team:
        :type opp_team: List[str]
        :param strength_state:
        :type strength_state: List[str]
        :param include:
        :type include: List[str]
        :param limit:
        :type limit: int
        :param offset:
        :type offset: int
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_pbp_serialize(
            season=season,
            sessions=sessions,
            game_id=game_id,
            play_id=play_id,
            event=event,
            player_1=player_1,
            goalie=goalie,
            event_team=event_team,
            opp_team=opp_team,
            strength_state=strength_state,
            include=include,
            limit=limit,
            offset=offset,
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "PbpResponse",
            '422': "HTTPValidationError",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _read_pbp_serialize(
        self,
        season,
        sessions,
        game_id,
        play_id,
        event,
        player_1,
        goalie,
        event_team,
        opp_team,
        strength_state,
        include,
        limit,
        offset,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'season': 'multi',
            'sessions': 'multi',
            'game_id': 'multi',
            'play_id': 'multi',
            'event': 'multi',
            'player_1': 'multi',
            'goalie': 'multi',
            'event_team': 'multi',
            'opp_team': 'multi',
            'strength_state': 'multi',
            'include': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if season is not None:
            
            _query_params.append(('season', season))
            
        if sessions is not None:
            
            _query_params.append(('sessions', sessions))
            
        if game_id is not None:
            
            _query_params.append(('game_id', game_id))
            
        if play_id is not None:
            
            _query_params.append(('play_id', play_id))
            
        if event is not None:
            
            _query_params.append(('event', event))
            
        if player_1 is not None:
            
            _query_params.append(('player_1', player_1))
            
        if goalie is not None:
            
            _query_params.append(('goalie', goalie))
            
        if event_team is not None:
            
            _query_params.append(('event_team', event_team))
            
        if opp_team is not None:
            
            _query_params.append(('opp_team', opp_team))
            
        if strength_state is not None:
            
            _query_params.append(('strength_state', strength_state))
            
        if include is not None:
            
            _query_params.append(('include', include))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'OAuth2PasswordBearer'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/chicken_nhl/play_by_play',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def read_pbp_game_ids(
        self,
        season: Optional[List[StrictInt]] = None,
        sessions: Optional[List[StrictStr]] = None,
        limit: Optional[Annotated[int, Field(le=50000, strict=True, ge=1)]] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> List[int]:
        """Read Pbp Game Ids


        :param season:
        :type season: List[int]
        :param sessions:
        :type sessions: List[str]
        :param limit:
        :type limit: int
        :param offset:
        :type offset: int
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_pbp_game_ids_serialize(
            season=season,
            sessions=sessions,
            limit=limit,
            offset=offset,
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[int]",
            '422': "HTTPValidationError",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def read_pbp_game_ids_with_http_info(
        self,
        season: Optional[List[StrictInt]] = None,
        sessions: Optional[List[StrictStr]] = None,
        limit: Optional[Annotated[int, Field(le=50000, strict=True, ge=1)]] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> ApiResponse[List[int]]:
        """Read Pbp Game Ids


        :param season:
        :type season: List[int]
        :param sessions:
        :type sessions: List[str]
        :param limit:
        :type limit: int
        :param offset:
        :type offset: int
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_pbp_game_ids_serialize(
            season=season,
            sessions=sessions,
            limit=limit,
            offset=offset,
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[int]",
            '422': "HTTPValidationError",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def read_pbp_game_ids_without_preload_content(
        self,
        season: Optional[List[StrictInt]] = None,
        sessions: Optional[List[StrictStr]] = None,
        limit: Optional[Annotated[int, Field(le=50000, strict=True, ge=1)]] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> RESTResponseType:
        """Read Pbp Game Ids


        :param season:
        :type season: List[int]
        :param sessions:
        :type sessions: List[str]
        :param limit:
        :type limit: int
        :param offset:
        :type offset: int
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_pbp_game_ids_serialize(
            season=season,
            sessions=sessions,
            limit=limit,
            offset=offset,
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[int]",
            '422': "HTTPValidationError",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _read_pbp_game_ids_serialize(
        self,
        season,
        sessions,
        limit,
        offset,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'season': 'multi',
            'sessions': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if season is not None:
            
            _query_params.append(('season', season))
            
        if sessions is not None:
            
            _query_params.append(('sessions', sessions))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'OAuth2PasswordBearer'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/chicken_nhl/play_by_play/game_ids',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def read_pbp_play_ids(
        self,
        season: Optional[List[StrictInt]] = None,
        sessions: Optional[List[StrictStr]] = None,
        game_id: Optional[List[StrictInt]] = None,
        limit: Optional[Annotated[int, Field(le=50000, strict=True, ge=1)]] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> List[int]:
        """Read Pbp Play Ids


        :param season:
        :type season: List[int]
        :param sessions:
        :type sessions: List[str]
        :param game_id:
        :type game_id: List[int]
        :param limit:
        :type limit: int
        :param offset:
        :type offset: int
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_pbp_play_ids_serialize(
            season=season,
            sessions=sessions,
            game_id=game_id,
            limit=limit,
            offset=offset,
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[int]",
            '422': "HTTPValidationError",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def read_pbp_play_ids_with_http_info(
        self,
        season: Optional[List[StrictInt]] = None,
        sessions: Optional[List[StrictStr]] = None,
        game_id: Optional[List[StrictInt]] = None,
        limit: Optional[Annotated[int, Field(le=50000, strict=True, ge=1)]] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> ApiResponse[List[int]]:
        """Read Pbp Play Ids


        :param season:
        :type season: List[int]
        :param sessions:
        :type sessions: List[str]
        :param game_id:
        :type game_id: List[int]
        :param limit:
        :type limit: int
        :param offset:
        :type offset: int
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_pbp_play_ids_serialize(
            season=season,
            sessions=sessions,
            game_id=game_id,
            limit=limit,
            offset=offset,
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[int]",
            '422': "HTTPValidationError",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def read_pbp_play_ids_without_preload_content(
        self,
        season: Optional[List[StrictInt]] = None,
        sessions: Optional[List[StrictStr]] = None,
        game_id: Optional[List[StrictInt]] = None,
        limit: Optional[Annotated[int, Field(le=50000, strict=True, ge=1)]] = None,
        offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = None,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> RESTResponseType:
        """Read Pbp Play Ids


        :param season:
        :type season: List[int]
        :param sessions:
        :type sessions: List[str]
        :param game_id:
        :type game_id: List[int]
        :param limit:
        :type limit: int
        :param offset:
        :type offset: int
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_pbp_play_ids_serialize(
            season=season,
            sessions=sessions,
            game_id=game_id,
            limit=limit,
            offset=offset,
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[int]",
            '422': "HTTPValidationError",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _read_pbp_play_ids_serialize(
        self,
        season,
        sessions,
        game_id,
        limit,
        offset,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'season': 'multi',
            'sessions': 'multi',
            'game_id': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if season is not None:
            
            _query_params.append(('season', season))
            
        if sessions is not None:
            
            _query_params.append(('sessions', sessions))
            
        if game_id is not None:
            
            _query_params.append(('game_id', game_id))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'OAuth2PasswordBearer'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/chicken_nhl/play_by_play/play_ids',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


