# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.7
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import StrictInt, StrictStr
from typing import List, Optional
from chickenstats_api.models.standings_response import StandingsResponse

from chickenstats_api.api_client import ApiClient, RequestSerialized
from chickenstats_api.api_response import ApiResponse
from chickenstats_api.rest import RESTResponseType


class StandingsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def read_standings(
        self,
        season: Optional[List[StrictInt]] = None,
        team: Optional[List[StrictStr]] = None,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> StandingsResponse:
        """Read Standings


        :param season:
        :type season: List[int]
        :param team:
        :type team: List[str]
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_standings_serialize(
            season=season,
            team=team,
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "StandingsResponse",
            '422': "HTTPValidationError",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def read_standings_with_http_info(
        self,
        season: Optional[List[StrictInt]] = None,
        team: Optional[List[StrictStr]] = None,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> ApiResponse[StandingsResponse]:
        """Read Standings


        :param season:
        :type season: List[int]
        :param team:
        :type team: List[str]
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_standings_serialize(
            season=season,
            team=team,
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "StandingsResponse",
            '422': "HTTPValidationError",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def read_standings_without_preload_content(
        self,
        season: Optional[List[StrictInt]] = None,
        team: Optional[List[StrictStr]] = None,
        _request_timeout: Optional[Union[float, Tuple[float, float]]] = None,
    ) -> RESTResponseType:
        """Read Standings


        :param season:
        :type season: List[int]
        :param team:
        :type team: List[str]
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._read_standings_serialize(
            season=season,
            team=team,
            _request_auth=None,
            _content_type=None,
            _headers=None,
            _host_index=0
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "StandingsResponse",
            '422': "HTTPValidationError",
        }

        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _read_standings_serialize(
        self,
        season,
        team,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'season': 'multi',
            'team': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if season is not None:
            
            _query_params.append(('season', season))
            
        if team is not None:
            
            _query_params.append(('team', team))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/chicken_nhl/standings',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


