# coding: utf-8

# flake8: noqa

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.6
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.6"

# Define package exports
__all__ = [
    "ChangesApi",
    "GamesApi",
    "InferenceApi",
    "LinesApi",
    "LiveApi",
    "LoginApi",
    "PlayByPlayApi",
    "PlayersApi",
    "RapmApi",
    "RostersApi",
    "ShiftsApi",
    "StandingsApi",
    "StatsApi",
    "TeamStatsApi",
    "TeamsApi",
    "UsersApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ChangesPublic",
    "ChangesResponse",
    "GamePublic",
    "GameResponse",
    "HTTPValidationError",
    "IdToken",
    "LinesCreate",
    "LinesGame",
    "LinesGameResponse",
    "LinesPublic",
    "LinesSeason",
    "LinesSeasonResponse",
    "LiveGamesPublic",
    "LivePbpPublic",
    "LivePbpResponse",
    "Message",
    "NewPassword",
    "PbpPublic",
    "PbpResponse",
    "PlayerPublic",
    "PlayerResponse",
    "PredGoalResponse",
    "PredGoalRow",
    "ProgrammaticCredentials",
    "RapmResponse",
    "RapmScores",
    "RosterPublic",
    "RosterResponse",
    "ShiftsPublic",
    "ShiftsResponse",
    "StandingsPublic",
    "StandingsResponse",
    "StatsCreate",
    "StatsGame",
    "StatsGameResponse",
    "StatsSeason",
    "StatsSeasonResponse",
    "TeamPublic",
    "TeamResponse",
    "TeamStatsCreate",
    "TeamStatsGame",
    "TeamStatsGameResponse",
    "TeamStatsPublic",
    "TeamStatsSeason",
    "TeamStatsSeasonResponse",
    "Token",
    "UpdatePassword",
    "UserCreate",
    "UserPublic",
    "UserRegister",
    "UserUpdate",
    "UserUpdateMe",
    "UsersPublic",
    "ValidationError",
    "ValidationErrorLocInner",
]

# import apis into sdk package
from chickenstats_api.api.changes_api import ChangesApi as ChangesApi
from chickenstats_api.api.games_api import GamesApi as GamesApi
from chickenstats_api.api.inference_api import InferenceApi as InferenceApi
from chickenstats_api.api.lines_api import LinesApi as LinesApi
from chickenstats_api.api.live_api import LiveApi as LiveApi
from chickenstats_api.api.login_api import LoginApi as LoginApi
from chickenstats_api.api.play_by_play_api import PlayByPlayApi as PlayByPlayApi
from chickenstats_api.api.players_api import PlayersApi as PlayersApi
from chickenstats_api.api.rapm_api import RapmApi as RapmApi
from chickenstats_api.api.rosters_api import RostersApi as RostersApi
from chickenstats_api.api.shifts_api import ShiftsApi as ShiftsApi
from chickenstats_api.api.standings_api import StandingsApi as StandingsApi
from chickenstats_api.api.stats_api import StatsApi as StatsApi
from chickenstats_api.api.team_stats_api import TeamStatsApi as TeamStatsApi
from chickenstats_api.api.teams_api import TeamsApi as TeamsApi
from chickenstats_api.api.users_api import UsersApi as UsersApi

# import ApiClient
from chickenstats_api.api_response import ApiResponse as ApiResponse
from chickenstats_api.api_client import ApiClient as ApiClient
from chickenstats_api.configuration import Configuration as Configuration
from chickenstats_api.exceptions import OpenApiException as OpenApiException
from chickenstats_api.exceptions import ApiTypeError as ApiTypeError
from chickenstats_api.exceptions import ApiValueError as ApiValueError
from chickenstats_api.exceptions import ApiKeyError as ApiKeyError
from chickenstats_api.exceptions import ApiAttributeError as ApiAttributeError
from chickenstats_api.exceptions import ApiException as ApiException

# import models into sdk package
from chickenstats_api.models.changes_public import ChangesPublic as ChangesPublic
from chickenstats_api.models.changes_response import ChangesResponse as ChangesResponse
from chickenstats_api.models.game_public import GamePublic as GamePublic
from chickenstats_api.models.game_response import GameResponse as GameResponse
from chickenstats_api.models.http_validation_error import HTTPValidationError as HTTPValidationError
from chickenstats_api.models.id_token import IdToken as IdToken
from chickenstats_api.models.lines_create import LinesCreate as LinesCreate
from chickenstats_api.models.lines_game import LinesGame as LinesGame
from chickenstats_api.models.lines_game_response import LinesGameResponse as LinesGameResponse
from chickenstats_api.models.lines_public import LinesPublic as LinesPublic
from chickenstats_api.models.lines_season import LinesSeason as LinesSeason
from chickenstats_api.models.lines_season_response import LinesSeasonResponse as LinesSeasonResponse
from chickenstats_api.models.live_games_public import LiveGamesPublic as LiveGamesPublic
from chickenstats_api.models.live_pbp_public import LivePbpPublic as LivePbpPublic
from chickenstats_api.models.live_pbp_response import LivePbpResponse as LivePbpResponse
from chickenstats_api.models.message import Message as Message
from chickenstats_api.models.new_password import NewPassword as NewPassword
from chickenstats_api.models.pbp_public import PbpPublic as PbpPublic
from chickenstats_api.models.pbp_response import PbpResponse as PbpResponse
from chickenstats_api.models.player_public import PlayerPublic as PlayerPublic
from chickenstats_api.models.player_response import PlayerResponse as PlayerResponse
from chickenstats_api.models.pred_goal_response import PredGoalResponse as PredGoalResponse
from chickenstats_api.models.pred_goal_row import PredGoalRow as PredGoalRow
from chickenstats_api.models.programmatic_credentials import ProgrammaticCredentials as ProgrammaticCredentials
from chickenstats_api.models.rapm_response import RapmResponse as RapmResponse
from chickenstats_api.models.rapm_scores import RapmScores as RapmScores
from chickenstats_api.models.roster_public import RosterPublic as RosterPublic
from chickenstats_api.models.roster_response import RosterResponse as RosterResponse
from chickenstats_api.models.shifts_public import ShiftsPublic as ShiftsPublic
from chickenstats_api.models.shifts_response import ShiftsResponse as ShiftsResponse
from chickenstats_api.models.standings_public import StandingsPublic as StandingsPublic
from chickenstats_api.models.standings_response import StandingsResponse as StandingsResponse
from chickenstats_api.models.stats_create import StatsCreate as StatsCreate
from chickenstats_api.models.stats_game import StatsGame as StatsGame
from chickenstats_api.models.stats_game_response import StatsGameResponse as StatsGameResponse
from chickenstats_api.models.stats_season import StatsSeason as StatsSeason
from chickenstats_api.models.stats_season_response import StatsSeasonResponse as StatsSeasonResponse
from chickenstats_api.models.team_public import TeamPublic as TeamPublic
from chickenstats_api.models.team_response import TeamResponse as TeamResponse
from chickenstats_api.models.team_stats_create import TeamStatsCreate as TeamStatsCreate
from chickenstats_api.models.team_stats_game import TeamStatsGame as TeamStatsGame
from chickenstats_api.models.team_stats_game_response import TeamStatsGameResponse as TeamStatsGameResponse
from chickenstats_api.models.team_stats_public import TeamStatsPublic as TeamStatsPublic
from chickenstats_api.models.team_stats_season import TeamStatsSeason as TeamStatsSeason
from chickenstats_api.models.team_stats_season_response import TeamStatsSeasonResponse as TeamStatsSeasonResponse
from chickenstats_api.models.token import Token as Token
from chickenstats_api.models.update_password import UpdatePassword as UpdatePassword
from chickenstats_api.models.user_create import UserCreate as UserCreate
from chickenstats_api.models.user_public import UserPublic as UserPublic
from chickenstats_api.models.user_register import UserRegister as UserRegister
from chickenstats_api.models.user_update import UserUpdate as UserUpdate
from chickenstats_api.models.user_update_me import UserUpdateMe as UserUpdateMe
from chickenstats_api.models.users_public import UsersPublic as UsersPublic
from chickenstats_api.models.validation_error import ValidationError as ValidationError
from chickenstats_api.models.validation_error_loc_inner import ValidationErrorLocInner as ValidationErrorLocInner
