# coding: utf-8

# flake8: noqa

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.4
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.4"

# Define package exports
__all__ = [
    "InferenceApi",
    "LinesApi",
    "LiveApi",
    "LoginApi",
    "PlayByPlayApi",
    "RapmApi",
    "StatsApi",
    "TeamStatsApi",
    "UsersApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "HTTPValidationError",
    "LinesCreate",
    "LinesGame",
    "LinesGameResponse",
    "LinesPublic",
    "LinesSeason",
    "LinesSeasonResponse",
    "LiveGamesPublic",
    "LivePbpPublic",
    "LivePbpResponse",
    "Message",
    "NewPassword",
    "PbpPublic",
    "PbpResponse",
    "PredGoalResponse",
    "PredGoalRow",
    "ProgrammaticCredentials",
    "RapmResponse",
    "RapmScores",
    "StatsCreate",
    "StatsGame",
    "StatsGameResponse",
    "StatsSeason",
    "StatsSeasonResponse",
    "TeamStatsCreate",
    "TeamStatsGame",
    "TeamStatsGameResponse",
    "TeamStatsPublic",
    "TeamStatsSeason",
    "TeamStatsSeasonResponse",
    "Token",
    "UpdatePassword",
    "UserCreate",
    "UserPublic",
    "UserRegister",
    "UserUpdate",
    "UserUpdateMe",
    "UsersPublic",
    "ValidationError",
    "ValidationErrorLocInner",
]

# import apis into sdk package
from chickenstats_api.api.inference_api import InferenceApi as InferenceApi
from chickenstats_api.api.lines_api import LinesApi as LinesApi
from chickenstats_api.api.live_api import LiveApi as LiveApi
from chickenstats_api.api.login_api import LoginApi as LoginApi
from chickenstats_api.api.play_by_play_api import PlayByPlayApi as PlayByPlayApi
from chickenstats_api.api.rapm_api import RapmApi as RapmApi
from chickenstats_api.api.stats_api import StatsApi as StatsApi
from chickenstats_api.api.team_stats_api import TeamStatsApi as TeamStatsApi
from chickenstats_api.api.users_api import UsersApi as UsersApi

# import ApiClient
from chickenstats_api.api_response import ApiResponse as ApiResponse
from chickenstats_api.api_client import ApiClient as ApiClient
from chickenstats_api.configuration import Configuration as Configuration
from chickenstats_api.exceptions import OpenApiException as OpenApiException
from chickenstats_api.exceptions import ApiTypeError as ApiTypeError
from chickenstats_api.exceptions import ApiValueError as ApiValueError
from chickenstats_api.exceptions import ApiKeyError as ApiKeyError
from chickenstats_api.exceptions import ApiAttributeError as ApiAttributeError
from chickenstats_api.exceptions import ApiException as ApiException

# import models into sdk package
from chickenstats_api.models.http_validation_error import HTTPValidationError as HTTPValidationError
from chickenstats_api.models.lines_create import LinesCreate as LinesCreate
from chickenstats_api.models.lines_game import LinesGame as LinesGame
from chickenstats_api.models.lines_game_response import LinesGameResponse as LinesGameResponse
from chickenstats_api.models.lines_public import LinesPublic as LinesPublic
from chickenstats_api.models.lines_season import LinesSeason as LinesSeason
from chickenstats_api.models.lines_season_response import LinesSeasonResponse as LinesSeasonResponse
from chickenstats_api.models.live_games_public import LiveGamesPublic as LiveGamesPublic
from chickenstats_api.models.live_pbp_public import LivePbpPublic as LivePbpPublic
from chickenstats_api.models.live_pbp_response import LivePbpResponse as LivePbpResponse
from chickenstats_api.models.message import Message as Message
from chickenstats_api.models.new_password import NewPassword as NewPassword
from chickenstats_api.models.pbp_public import PbpPublic as PbpPublic
from chickenstats_api.models.pbp_response import PbpResponse as PbpResponse
from chickenstats_api.models.pred_goal_response import PredGoalResponse as PredGoalResponse
from chickenstats_api.models.pred_goal_row import PredGoalRow as PredGoalRow
from chickenstats_api.models.programmatic_credentials import ProgrammaticCredentials as ProgrammaticCredentials
from chickenstats_api.models.rapm_response import RapmResponse as RapmResponse
from chickenstats_api.models.rapm_scores import RapmScores as RapmScores
from chickenstats_api.models.stats_create import StatsCreate as StatsCreate
from chickenstats_api.models.stats_game import StatsGame as StatsGame
from chickenstats_api.models.stats_game_response import StatsGameResponse as StatsGameResponse
from chickenstats_api.models.stats_season import StatsSeason as StatsSeason
from chickenstats_api.models.stats_season_response import StatsSeasonResponse as StatsSeasonResponse
from chickenstats_api.models.team_stats_create import TeamStatsCreate as TeamStatsCreate
from chickenstats_api.models.team_stats_game import TeamStatsGame as TeamStatsGame
from chickenstats_api.models.team_stats_game_response import TeamStatsGameResponse as TeamStatsGameResponse
from chickenstats_api.models.team_stats_public import TeamStatsPublic as TeamStatsPublic
from chickenstats_api.models.team_stats_season import TeamStatsSeason as TeamStatsSeason
from chickenstats_api.models.team_stats_season_response import TeamStatsSeasonResponse as TeamStatsSeasonResponse
from chickenstats_api.models.token import Token as Token
from chickenstats_api.models.update_password import UpdatePassword as UpdatePassword
from chickenstats_api.models.user_create import UserCreate as UserCreate
from chickenstats_api.models.user_public import UserPublic as UserPublic
from chickenstats_api.models.user_register import UserRegister as UserRegister
from chickenstats_api.models.user_update import UserUpdate as UserUpdate
from chickenstats_api.models.user_update_me import UserUpdateMe as UserUpdateMe
from chickenstats_api.models.users_public import UsersPublic as UsersPublic
from chickenstats_api.models.validation_error import ValidationError as ValidationError
from chickenstats_api.models.validation_error_loc_inner import ValidationErrorLocInner as ValidationErrorLocInner
