# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.6
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from chickenstats_api.models.game_public import GamePublic
from typing import Optional, Set
from typing_extensions import Self

class ChangesPublic(BaseModel):
    """
    ChangesPublic
    """ # noqa: E501
    season: StrictInt
    session: StrictStr
    game_id: StrictInt
    event_team: StrictStr
    event: Optional[StrictStr] = None
    event_type: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    period: StrictInt
    period_seconds: StrictInt
    game_seconds: StrictInt
    change_on_count: Optional[StrictInt] = None
    change_off_count: Optional[StrictInt] = None
    change_on_api_id: Optional[StrictStr] = None
    change_off_api_id: Optional[StrictStr] = None
    change_on_forwards_count: Optional[StrictInt] = None
    change_off_forwards_count: Optional[StrictInt] = None
    change_on_forwards_api_id: Optional[StrictStr] = None
    change_off_forwards_api_id: Optional[StrictStr] = None
    change_on_defense_count: Optional[StrictInt] = None
    change_off_defense_count: Optional[StrictInt] = None
    change_on_defense_api_id: Optional[StrictStr] = None
    change_off_defense_api_id: Optional[StrictStr] = None
    change_on_goalie_count: Optional[StrictInt] = None
    change_off_goalie_count: Optional[StrictInt] = None
    change_on_goalie_api_id: Optional[StrictStr] = None
    change_off_goalie_api_id: Optional[StrictStr] = None
    is_home: StrictInt
    game: Optional[GamePublic] = None
    __properties: ClassVar[List[str]] = ["season", "session", "game_id", "event_team", "event", "event_type", "description", "period", "period_seconds", "game_seconds", "change_on_count", "change_off_count", "change_on_api_id", "change_off_api_id", "change_on_forwards_count", "change_off_forwards_count", "change_on_forwards_api_id", "change_off_forwards_api_id", "change_on_defense_count", "change_off_defense_count", "change_on_defense_api_id", "change_off_defense_api_id", "change_on_goalie_count", "change_off_goalie_count", "change_on_goalie_api_id", "change_off_goalie_api_id", "is_home", "game"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChangesPublic from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of game
        if self.game:
            _dict['game'] = self.game.to_dict()
        # set to None if event (nullable) is None
        # and model_fields_set contains the field
        if self.event is None and "event" in self.model_fields_set:
            _dict['event'] = None

        # set to None if event_type (nullable) is None
        # and model_fields_set contains the field
        if self.event_type is None and "event_type" in self.model_fields_set:
            _dict['event_type'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if change_on_count (nullable) is None
        # and model_fields_set contains the field
        if self.change_on_count is None and "change_on_count" in self.model_fields_set:
            _dict['change_on_count'] = None

        # set to None if change_off_count (nullable) is None
        # and model_fields_set contains the field
        if self.change_off_count is None and "change_off_count" in self.model_fields_set:
            _dict['change_off_count'] = None

        # set to None if change_on_api_id (nullable) is None
        # and model_fields_set contains the field
        if self.change_on_api_id is None and "change_on_api_id" in self.model_fields_set:
            _dict['change_on_api_id'] = None

        # set to None if change_off_api_id (nullable) is None
        # and model_fields_set contains the field
        if self.change_off_api_id is None and "change_off_api_id" in self.model_fields_set:
            _dict['change_off_api_id'] = None

        # set to None if change_on_forwards_count (nullable) is None
        # and model_fields_set contains the field
        if self.change_on_forwards_count is None and "change_on_forwards_count" in self.model_fields_set:
            _dict['change_on_forwards_count'] = None

        # set to None if change_off_forwards_count (nullable) is None
        # and model_fields_set contains the field
        if self.change_off_forwards_count is None and "change_off_forwards_count" in self.model_fields_set:
            _dict['change_off_forwards_count'] = None

        # set to None if change_on_forwards_api_id (nullable) is None
        # and model_fields_set contains the field
        if self.change_on_forwards_api_id is None and "change_on_forwards_api_id" in self.model_fields_set:
            _dict['change_on_forwards_api_id'] = None

        # set to None if change_off_forwards_api_id (nullable) is None
        # and model_fields_set contains the field
        if self.change_off_forwards_api_id is None and "change_off_forwards_api_id" in self.model_fields_set:
            _dict['change_off_forwards_api_id'] = None

        # set to None if change_on_defense_count (nullable) is None
        # and model_fields_set contains the field
        if self.change_on_defense_count is None and "change_on_defense_count" in self.model_fields_set:
            _dict['change_on_defense_count'] = None

        # set to None if change_off_defense_count (nullable) is None
        # and model_fields_set contains the field
        if self.change_off_defense_count is None and "change_off_defense_count" in self.model_fields_set:
            _dict['change_off_defense_count'] = None

        # set to None if change_on_defense_api_id (nullable) is None
        # and model_fields_set contains the field
        if self.change_on_defense_api_id is None and "change_on_defense_api_id" in self.model_fields_set:
            _dict['change_on_defense_api_id'] = None

        # set to None if change_off_defense_api_id (nullable) is None
        # and model_fields_set contains the field
        if self.change_off_defense_api_id is None and "change_off_defense_api_id" in self.model_fields_set:
            _dict['change_off_defense_api_id'] = None

        # set to None if change_on_goalie_count (nullable) is None
        # and model_fields_set contains the field
        if self.change_on_goalie_count is None and "change_on_goalie_count" in self.model_fields_set:
            _dict['change_on_goalie_count'] = None

        # set to None if change_off_goalie_count (nullable) is None
        # and model_fields_set contains the field
        if self.change_off_goalie_count is None and "change_off_goalie_count" in self.model_fields_set:
            _dict['change_off_goalie_count'] = None

        # set to None if change_on_goalie_api_id (nullable) is None
        # and model_fields_set contains the field
        if self.change_on_goalie_api_id is None and "change_on_goalie_api_id" in self.model_fields_set:
            _dict['change_on_goalie_api_id'] = None

        # set to None if change_off_goalie_api_id (nullable) is None
        # and model_fields_set contains the field
        if self.change_off_goalie_api_id is None and "change_off_goalie_api_id" in self.model_fields_set:
            _dict['change_off_goalie_api_id'] = None

        # set to None if game (nullable) is None
        # and model_fields_set contains the field
        if self.game is None and "game" in self.model_fields_set:
            _dict['game'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChangesPublic from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "season": obj.get("season"),
            "session": obj.get("session"),
            "game_id": obj.get("game_id"),
            "event_team": obj.get("event_team"),
            "event": obj.get("event"),
            "event_type": obj.get("event_type"),
            "description": obj.get("description"),
            "period": obj.get("period"),
            "period_seconds": obj.get("period_seconds"),
            "game_seconds": obj.get("game_seconds"),
            "change_on_count": obj.get("change_on_count"),
            "change_off_count": obj.get("change_off_count"),
            "change_on_api_id": obj.get("change_on_api_id"),
            "change_off_api_id": obj.get("change_off_api_id"),
            "change_on_forwards_count": obj.get("change_on_forwards_count"),
            "change_off_forwards_count": obj.get("change_off_forwards_count"),
            "change_on_forwards_api_id": obj.get("change_on_forwards_api_id"),
            "change_off_forwards_api_id": obj.get("change_off_forwards_api_id"),
            "change_on_defense_count": obj.get("change_on_defense_count"),
            "change_off_defense_count": obj.get("change_off_defense_count"),
            "change_on_defense_api_id": obj.get("change_on_defense_api_id"),
            "change_off_defense_api_id": obj.get("change_off_defense_api_id"),
            "change_on_goalie_count": obj.get("change_on_goalie_count"),
            "change_off_goalie_count": obj.get("change_off_goalie_count"),
            "change_on_goalie_api_id": obj.get("change_on_goalie_api_id"),
            "change_off_goalie_api_id": obj.get("change_off_goalie_api_id"),
            "is_home": obj.get("is_home"),
            "game": GamePublic.from_dict(obj["game"]) if obj.get("game") is not None else None
        })
        return _obj


