# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.5
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GamePublic(BaseModel):
    """
    GamePublic
    """ # noqa: E501
    game_id: StrictInt
    season: StrictInt
    session: StrictStr
    game_date: StrictStr
    start_time: Optional[StrictStr] = None
    start_time_utc: Optional[datetime] = None
    game_state: Optional[StrictStr] = None
    game_schedule_state: Optional[StrictStr] = None
    game_outcome: Optional[StrictStr] = None
    home_team: StrictStr
    away_team: StrictStr
    home_score: Optional[StrictInt] = None
    away_score: Optional[StrictInt] = None
    venue: Optional[StrictStr] = None
    venue_location: Optional[StrictStr] = None
    venue_timezone: Optional[StrictStr] = None
    neutral_site: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["game_id", "season", "session", "game_date", "start_time", "start_time_utc", "game_state", "game_schedule_state", "game_outcome", "home_team", "away_team", "home_score", "away_score", "venue", "venue_location", "venue_timezone", "neutral_site"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GamePublic from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if start_time (nullable) is None
        # and model_fields_set contains the field
        if self.start_time is None and "start_time" in self.model_fields_set:
            _dict['start_time'] = None

        # set to None if start_time_utc (nullable) is None
        # and model_fields_set contains the field
        if self.start_time_utc is None and "start_time_utc" in self.model_fields_set:
            _dict['start_time_utc'] = None

        # set to None if game_state (nullable) is None
        # and model_fields_set contains the field
        if self.game_state is None and "game_state" in self.model_fields_set:
            _dict['game_state'] = None

        # set to None if game_schedule_state (nullable) is None
        # and model_fields_set contains the field
        if self.game_schedule_state is None and "game_schedule_state" in self.model_fields_set:
            _dict['game_schedule_state'] = None

        # set to None if game_outcome (nullable) is None
        # and model_fields_set contains the field
        if self.game_outcome is None and "game_outcome" in self.model_fields_set:
            _dict['game_outcome'] = None

        # set to None if home_score (nullable) is None
        # and model_fields_set contains the field
        if self.home_score is None and "home_score" in self.model_fields_set:
            _dict['home_score'] = None

        # set to None if away_score (nullable) is None
        # and model_fields_set contains the field
        if self.away_score is None and "away_score" in self.model_fields_set:
            _dict['away_score'] = None

        # set to None if venue (nullable) is None
        # and model_fields_set contains the field
        if self.venue is None and "venue" in self.model_fields_set:
            _dict['venue'] = None

        # set to None if venue_location (nullable) is None
        # and model_fields_set contains the field
        if self.venue_location is None and "venue_location" in self.model_fields_set:
            _dict['venue_location'] = None

        # set to None if venue_timezone (nullable) is None
        # and model_fields_set contains the field
        if self.venue_timezone is None and "venue_timezone" in self.model_fields_set:
            _dict['venue_timezone'] = None

        # set to None if neutral_site (nullable) is None
        # and model_fields_set contains the field
        if self.neutral_site is None and "neutral_site" in self.model_fields_set:
            _dict['neutral_site'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GamePublic from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "game_id": obj.get("game_id"),
            "season": obj.get("season"),
            "session": obj.get("session"),
            "game_date": obj.get("game_date"),
            "start_time": obj.get("start_time"),
            "start_time_utc": obj.get("start_time_utc"),
            "game_state": obj.get("game_state"),
            "game_schedule_state": obj.get("game_schedule_state"),
            "game_outcome": obj.get("game_outcome"),
            "home_team": obj.get("home_team"),
            "away_team": obj.get("away_team"),
            "home_score": obj.get("home_score"),
            "away_score": obj.get("away_score"),
            "venue": obj.get("venue"),
            "venue_location": obj.get("venue_location"),
            "venue_timezone": obj.get("venue_timezone"),
            "neutral_site": obj.get("neutral_site")
        })
        return _obj


