# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.5
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class LiveGamesPublic(BaseModel):
    """
    LiveGamesPublic
    """ # noqa: E501
    game_id: StrictInt
    game_date: Optional[StrictStr]
    home_team: Optional[StrictStr]
    away_team: Optional[StrictStr]
    game_state: StrictStr
    period: Optional[StrictInt]
    time_remaining: Optional[StrictStr]
    home_score: StrictInt
    away_score: StrictInt
    last_updated: datetime
    __properties: ClassVar[List[str]] = ["game_id", "game_date", "home_team", "away_team", "game_state", "period", "time_remaining", "home_score", "away_score", "last_updated"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LiveGamesPublic from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if game_date (nullable) is None
        # and model_fields_set contains the field
        if self.game_date is None and "game_date" in self.model_fields_set:
            _dict['game_date'] = None

        # set to None if home_team (nullable) is None
        # and model_fields_set contains the field
        if self.home_team is None and "home_team" in self.model_fields_set:
            _dict['home_team'] = None

        # set to None if away_team (nullable) is None
        # and model_fields_set contains the field
        if self.away_team is None and "away_team" in self.model_fields_set:
            _dict['away_team'] = None

        # set to None if period (nullable) is None
        # and model_fields_set contains the field
        if self.period is None and "period" in self.model_fields_set:
            _dict['period'] = None

        # set to None if time_remaining (nullable) is None
        # and model_fields_set contains the field
        if self.time_remaining is None and "time_remaining" in self.model_fields_set:
            _dict['time_remaining'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LiveGamesPublic from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "game_id": obj.get("game_id"),
            "game_date": obj.get("game_date"),
            "home_team": obj.get("home_team"),
            "away_team": obj.get("away_team"),
            "game_state": obj.get("game_state"),
            "period": obj.get("period"),
            "time_remaining": obj.get("time_remaining"),
            "home_score": obj.get("home_score"),
            "away_score": obj.get("away_score"),
            "last_updated": obj.get("last_updated")
        })
        return _obj


