# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.7
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class PlayerPublic(BaseModel):
    """
    PlayerPublic
    """ # noqa: E501
    api_id: StrictInt
    eh_id: Optional[StrictStr] = None
    name: StrictStr
    position: Optional[StrictStr] = None
    shoots: Optional[StrictStr] = None
    catches: Optional[StrictStr] = None
    birth_date: Optional[date] = None
    birth_city: Optional[StrictStr] = None
    birth_state_province: Optional[StrictStr] = None
    birth_country: Optional[StrictStr] = None
    nationality: Optional[StrictStr] = None
    height: Optional[Union[StrictFloat, StrictInt]] = None
    weight: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["api_id", "eh_id", "name", "position", "shoots", "catches", "birth_date", "birth_city", "birth_state_province", "birth_country", "nationality", "height", "weight"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlayerPublic from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if eh_id (nullable) is None
        # and model_fields_set contains the field
        if self.eh_id is None and "eh_id" in self.model_fields_set:
            _dict['eh_id'] = None

        # set to None if position (nullable) is None
        # and model_fields_set contains the field
        if self.position is None and "position" in self.model_fields_set:
            _dict['position'] = None

        # set to None if shoots (nullable) is None
        # and model_fields_set contains the field
        if self.shoots is None and "shoots" in self.model_fields_set:
            _dict['shoots'] = None

        # set to None if catches (nullable) is None
        # and model_fields_set contains the field
        if self.catches is None and "catches" in self.model_fields_set:
            _dict['catches'] = None

        # set to None if birth_date (nullable) is None
        # and model_fields_set contains the field
        if self.birth_date is None and "birth_date" in self.model_fields_set:
            _dict['birth_date'] = None

        # set to None if birth_city (nullable) is None
        # and model_fields_set contains the field
        if self.birth_city is None and "birth_city" in self.model_fields_set:
            _dict['birth_city'] = None

        # set to None if birth_state_province (nullable) is None
        # and model_fields_set contains the field
        if self.birth_state_province is None and "birth_state_province" in self.model_fields_set:
            _dict['birth_state_province'] = None

        # set to None if birth_country (nullable) is None
        # and model_fields_set contains the field
        if self.birth_country is None and "birth_country" in self.model_fields_set:
            _dict['birth_country'] = None

        # set to None if nationality (nullable) is None
        # and model_fields_set contains the field
        if self.nationality is None and "nationality" in self.model_fields_set:
            _dict['nationality'] = None

        # set to None if height (nullable) is None
        # and model_fields_set contains the field
        if self.height is None and "height" in self.model_fields_set:
            _dict['height'] = None

        # set to None if weight (nullable) is None
        # and model_fields_set contains the field
        if self.weight is None and "weight" in self.model_fields_set:
            _dict['weight'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlayerPublic from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "api_id": obj.get("api_id"),
            "eh_id": obj.get("eh_id"),
            "name": obj.get("name"),
            "position": obj.get("position"),
            "shoots": obj.get("shoots"),
            "catches": obj.get("catches"),
            "birth_date": obj.get("birth_date"),
            "birth_city": obj.get("birth_city"),
            "birth_state_province": obj.get("birth_state_province"),
            "birth_country": obj.get("birth_country"),
            "nationality": obj.get("nationality"),
            "height": obj.get("height"),
            "weight": obj.get("weight")
        })
        return _obj


