# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.6
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ProgrammaticCredentials(BaseModel):
    """
    ProgrammaticCredentials
    """ # noqa: E501
    cf_client_id: StrictStr
    cf_client_secret: Optional[StrictStr] = None
    token_endpoint: Optional[StrictStr] = 'POST /api/v1/login/firebase-token'
    note: Optional[StrictStr] = 'The secret is shown once. Store it securely — rotate if lost.'
    __properties: ClassVar[List[str]] = ["cf_client_id", "cf_client_secret", "token_endpoint", "note"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProgrammaticCredentials from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if cf_client_secret (nullable) is None
        # and model_fields_set contains the field
        if self.cf_client_secret is None and "cf_client_secret" in self.model_fields_set:
            _dict['cf_client_secret'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProgrammaticCredentials from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cf_client_id": obj.get("cf_client_id"),
            "cf_client_secret": obj.get("cf_client_secret"),
            "token_endpoint": obj.get("token_endpoint") if obj.get("token_endpoint") is not None else 'POST /api/v1/login/firebase-token',
            "note": obj.get("note") if obj.get("note") is not None else 'The secret is shown once. Store it securely — rotate if lost.'
        })
        return _obj


