# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.6
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class RapmScores(BaseModel):
    """
    RapmScores
    """ # noqa: E501
    id: StrictStr
    api_id: StrictInt
    season: StrictInt
    session: StrictStr
    situation: StrictStr
    team: Optional[StrictStr] = None
    pos: Optional[StrictStr] = None
    pos2: Optional[StrictStr] = None
    toi_minutes: Optional[Union[StrictFloat, StrictInt]] = None
    rapm_off: Optional[Union[StrictFloat, StrictInt]] = None
    rapm_def: Optional[Union[StrictFloat, StrictInt]] = None
    off_coeff_corsi: Optional[Union[StrictFloat, StrictInt]] = None
    off_coeff_goals: Optional[Union[StrictFloat, StrictInt]] = None
    def_coeff_corsi: Optional[Union[StrictFloat, StrictInt]] = None
    def_coeff_goals: Optional[Union[StrictFloat, StrictInt]] = None
    metric_for_context_xg: Optional[Union[StrictFloat, StrictInt]] = None
    metric_against_context_xg: Optional[Union[StrictFloat, StrictInt]] = None
    metric_diff_context_xg: Optional[Union[StrictFloat, StrictInt]] = None
    metric_for_corsi: Optional[Union[StrictFloat, StrictInt]] = None
    metric_against_corsi: Optional[Union[StrictFloat, StrictInt]] = None
    metric_diff_corsi: Optional[Union[StrictFloat, StrictInt]] = None
    metric_for_goals: Optional[Union[StrictFloat, StrictInt]] = None
    metric_against_goals: Optional[Union[StrictFloat, StrictInt]] = None
    metric_diff_goals: Optional[Union[StrictFloat, StrictInt]] = None
    on_ice_for_60_context_xg: Optional[Union[StrictFloat, StrictInt]] = None
    on_ice_against_60_context_xg: Optional[Union[StrictFloat, StrictInt]] = None
    on_ice_diff_60_context_xg: Optional[Union[StrictFloat, StrictInt]] = None
    on_ice_for_60_corsi: Optional[Union[StrictFloat, StrictInt]] = None
    on_ice_against_60_corsi: Optional[Union[StrictFloat, StrictInt]] = None
    on_ice_diff_60_corsi: Optional[Union[StrictFloat, StrictInt]] = None
    on_ice_for_60_goals: Optional[Union[StrictFloat, StrictInt]] = None
    on_ice_against_60_goals: Optional[Union[StrictFloat, StrictInt]] = None
    on_ice_diff_60_goals: Optional[Union[StrictFloat, StrictInt]] = None
    total_rapm_context_xg: Optional[Union[StrictFloat, StrictInt]] = None
    total_rapm_corsi: Optional[Union[StrictFloat, StrictInt]] = None
    total_rapm_goals: Optional[Union[StrictFloat, StrictInt]] = None
    off_coeff_context_xg_z: Optional[Union[StrictFloat, StrictInt]] = None
    off_coeff_corsi_z: Optional[Union[StrictFloat, StrictInt]] = None
    off_coeff_goals_z: Optional[Union[StrictFloat, StrictInt]] = None
    def_coeff_context_xg_z: Optional[Union[StrictFloat, StrictInt]] = None
    def_coeff_corsi_z: Optional[Union[StrictFloat, StrictInt]] = None
    def_coeff_goals_z: Optional[Union[StrictFloat, StrictInt]] = None
    metric_for_context_xg_z: Optional[Union[StrictFloat, StrictInt]] = None
    metric_against_context_xg_z: Optional[Union[StrictFloat, StrictInt]] = None
    metric_diff_context_xg_z: Optional[Union[StrictFloat, StrictInt]] = None
    metric_for_corsi_z: Optional[Union[StrictFloat, StrictInt]] = None
    metric_against_corsi_z: Optional[Union[StrictFloat, StrictInt]] = None
    metric_diff_corsi_z: Optional[Union[StrictFloat, StrictInt]] = None
    metric_for_goals_z: Optional[Union[StrictFloat, StrictInt]] = None
    metric_against_goals_z: Optional[Union[StrictFloat, StrictInt]] = None
    metric_diff_goals_z: Optional[Union[StrictFloat, StrictInt]] = None
    on_ice_for_60_context_xg_z: Optional[Union[StrictFloat, StrictInt]] = None
    on_ice_against_60_context_xg_z: Optional[Union[StrictFloat, StrictInt]] = None
    on_ice_diff_60_context_xg_z: Optional[Union[StrictFloat, StrictInt]] = None
    on_ice_for_60_corsi_z: Optional[Union[StrictFloat, StrictInt]] = None
    on_ice_against_60_corsi_z: Optional[Union[StrictFloat, StrictInt]] = None
    on_ice_diff_60_corsi_z: Optional[Union[StrictFloat, StrictInt]] = None
    on_ice_for_60_goals_z: Optional[Union[StrictFloat, StrictInt]] = None
    on_ice_against_60_goals_z: Optional[Union[StrictFloat, StrictInt]] = None
    on_ice_diff_60_goals_z: Optional[Union[StrictFloat, StrictInt]] = None
    total_rapm_context_xg_z: Optional[Union[StrictFloat, StrictInt]] = None
    total_rapm_corsi_z: Optional[Union[StrictFloat, StrictInt]] = None
    total_rapm_goals_z: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["id", "api_id", "season", "session", "situation", "team", "pos", "pos2", "toi_minutes", "rapm_off", "rapm_def", "off_coeff_corsi", "off_coeff_goals", "def_coeff_corsi", "def_coeff_goals", "metric_for_context_xg", "metric_against_context_xg", "metric_diff_context_xg", "metric_for_corsi", "metric_against_corsi", "metric_diff_corsi", "metric_for_goals", "metric_against_goals", "metric_diff_goals", "on_ice_for_60_context_xg", "on_ice_against_60_context_xg", "on_ice_diff_60_context_xg", "on_ice_for_60_corsi", "on_ice_against_60_corsi", "on_ice_diff_60_corsi", "on_ice_for_60_goals", "on_ice_against_60_goals", "on_ice_diff_60_goals", "total_rapm_context_xg", "total_rapm_corsi", "total_rapm_goals", "off_coeff_context_xg_z", "off_coeff_corsi_z", "off_coeff_goals_z", "def_coeff_context_xg_z", "def_coeff_corsi_z", "def_coeff_goals_z", "metric_for_context_xg_z", "metric_against_context_xg_z", "metric_diff_context_xg_z", "metric_for_corsi_z", "metric_against_corsi_z", "metric_diff_corsi_z", "metric_for_goals_z", "metric_against_goals_z", "metric_diff_goals_z", "on_ice_for_60_context_xg_z", "on_ice_against_60_context_xg_z", "on_ice_diff_60_context_xg_z", "on_ice_for_60_corsi_z", "on_ice_against_60_corsi_z", "on_ice_diff_60_corsi_z", "on_ice_for_60_goals_z", "on_ice_against_60_goals_z", "on_ice_diff_60_goals_z", "total_rapm_context_xg_z", "total_rapm_corsi_z", "total_rapm_goals_z"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RapmScores from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if team (nullable) is None
        # and model_fields_set contains the field
        if self.team is None and "team" in self.model_fields_set:
            _dict['team'] = None

        # set to None if pos (nullable) is None
        # and model_fields_set contains the field
        if self.pos is None and "pos" in self.model_fields_set:
            _dict['pos'] = None

        # set to None if pos2 (nullable) is None
        # and model_fields_set contains the field
        if self.pos2 is None and "pos2" in self.model_fields_set:
            _dict['pos2'] = None

        # set to None if toi_minutes (nullable) is None
        # and model_fields_set contains the field
        if self.toi_minutes is None and "toi_minutes" in self.model_fields_set:
            _dict['toi_minutes'] = None

        # set to None if rapm_off (nullable) is None
        # and model_fields_set contains the field
        if self.rapm_off is None and "rapm_off" in self.model_fields_set:
            _dict['rapm_off'] = None

        # set to None if rapm_def (nullable) is None
        # and model_fields_set contains the field
        if self.rapm_def is None and "rapm_def" in self.model_fields_set:
            _dict['rapm_def'] = None

        # set to None if off_coeff_corsi (nullable) is None
        # and model_fields_set contains the field
        if self.off_coeff_corsi is None and "off_coeff_corsi" in self.model_fields_set:
            _dict['off_coeff_corsi'] = None

        # set to None if off_coeff_goals (nullable) is None
        # and model_fields_set contains the field
        if self.off_coeff_goals is None and "off_coeff_goals" in self.model_fields_set:
            _dict['off_coeff_goals'] = None

        # set to None if def_coeff_corsi (nullable) is None
        # and model_fields_set contains the field
        if self.def_coeff_corsi is None and "def_coeff_corsi" in self.model_fields_set:
            _dict['def_coeff_corsi'] = None

        # set to None if def_coeff_goals (nullable) is None
        # and model_fields_set contains the field
        if self.def_coeff_goals is None and "def_coeff_goals" in self.model_fields_set:
            _dict['def_coeff_goals'] = None

        # set to None if metric_for_context_xg (nullable) is None
        # and model_fields_set contains the field
        if self.metric_for_context_xg is None and "metric_for_context_xg" in self.model_fields_set:
            _dict['metric_for_context_xg'] = None

        # set to None if metric_against_context_xg (nullable) is None
        # and model_fields_set contains the field
        if self.metric_against_context_xg is None and "metric_against_context_xg" in self.model_fields_set:
            _dict['metric_against_context_xg'] = None

        # set to None if metric_diff_context_xg (nullable) is None
        # and model_fields_set contains the field
        if self.metric_diff_context_xg is None and "metric_diff_context_xg" in self.model_fields_set:
            _dict['metric_diff_context_xg'] = None

        # set to None if metric_for_corsi (nullable) is None
        # and model_fields_set contains the field
        if self.metric_for_corsi is None and "metric_for_corsi" in self.model_fields_set:
            _dict['metric_for_corsi'] = None

        # set to None if metric_against_corsi (nullable) is None
        # and model_fields_set contains the field
        if self.metric_against_corsi is None and "metric_against_corsi" in self.model_fields_set:
            _dict['metric_against_corsi'] = None

        # set to None if metric_diff_corsi (nullable) is None
        # and model_fields_set contains the field
        if self.metric_diff_corsi is None and "metric_diff_corsi" in self.model_fields_set:
            _dict['metric_diff_corsi'] = None

        # set to None if metric_for_goals (nullable) is None
        # and model_fields_set contains the field
        if self.metric_for_goals is None and "metric_for_goals" in self.model_fields_set:
            _dict['metric_for_goals'] = None

        # set to None if metric_against_goals (nullable) is None
        # and model_fields_set contains the field
        if self.metric_against_goals is None and "metric_against_goals" in self.model_fields_set:
            _dict['metric_against_goals'] = None

        # set to None if metric_diff_goals (nullable) is None
        # and model_fields_set contains the field
        if self.metric_diff_goals is None and "metric_diff_goals" in self.model_fields_set:
            _dict['metric_diff_goals'] = None

        # set to None if on_ice_for_60_context_xg (nullable) is None
        # and model_fields_set contains the field
        if self.on_ice_for_60_context_xg is None and "on_ice_for_60_context_xg" in self.model_fields_set:
            _dict['on_ice_for_60_context_xg'] = None

        # set to None if on_ice_against_60_context_xg (nullable) is None
        # and model_fields_set contains the field
        if self.on_ice_against_60_context_xg is None and "on_ice_against_60_context_xg" in self.model_fields_set:
            _dict['on_ice_against_60_context_xg'] = None

        # set to None if on_ice_diff_60_context_xg (nullable) is None
        # and model_fields_set contains the field
        if self.on_ice_diff_60_context_xg is None and "on_ice_diff_60_context_xg" in self.model_fields_set:
            _dict['on_ice_diff_60_context_xg'] = None

        # set to None if on_ice_for_60_corsi (nullable) is None
        # and model_fields_set contains the field
        if self.on_ice_for_60_corsi is None and "on_ice_for_60_corsi" in self.model_fields_set:
            _dict['on_ice_for_60_corsi'] = None

        # set to None if on_ice_against_60_corsi (nullable) is None
        # and model_fields_set contains the field
        if self.on_ice_against_60_corsi is None and "on_ice_against_60_corsi" in self.model_fields_set:
            _dict['on_ice_against_60_corsi'] = None

        # set to None if on_ice_diff_60_corsi (nullable) is None
        # and model_fields_set contains the field
        if self.on_ice_diff_60_corsi is None and "on_ice_diff_60_corsi" in self.model_fields_set:
            _dict['on_ice_diff_60_corsi'] = None

        # set to None if on_ice_for_60_goals (nullable) is None
        # and model_fields_set contains the field
        if self.on_ice_for_60_goals is None and "on_ice_for_60_goals" in self.model_fields_set:
            _dict['on_ice_for_60_goals'] = None

        # set to None if on_ice_against_60_goals (nullable) is None
        # and model_fields_set contains the field
        if self.on_ice_against_60_goals is None and "on_ice_against_60_goals" in self.model_fields_set:
            _dict['on_ice_against_60_goals'] = None

        # set to None if on_ice_diff_60_goals (nullable) is None
        # and model_fields_set contains the field
        if self.on_ice_diff_60_goals is None and "on_ice_diff_60_goals" in self.model_fields_set:
            _dict['on_ice_diff_60_goals'] = None

        # set to None if total_rapm_context_xg (nullable) is None
        # and model_fields_set contains the field
        if self.total_rapm_context_xg is None and "total_rapm_context_xg" in self.model_fields_set:
            _dict['total_rapm_context_xg'] = None

        # set to None if total_rapm_corsi (nullable) is None
        # and model_fields_set contains the field
        if self.total_rapm_corsi is None and "total_rapm_corsi" in self.model_fields_set:
            _dict['total_rapm_corsi'] = None

        # set to None if total_rapm_goals (nullable) is None
        # and model_fields_set contains the field
        if self.total_rapm_goals is None and "total_rapm_goals" in self.model_fields_set:
            _dict['total_rapm_goals'] = None

        # set to None if off_coeff_context_xg_z (nullable) is None
        # and model_fields_set contains the field
        if self.off_coeff_context_xg_z is None and "off_coeff_context_xg_z" in self.model_fields_set:
            _dict['off_coeff_context_xg_z'] = None

        # set to None if off_coeff_corsi_z (nullable) is None
        # and model_fields_set contains the field
        if self.off_coeff_corsi_z is None and "off_coeff_corsi_z" in self.model_fields_set:
            _dict['off_coeff_corsi_z'] = None

        # set to None if off_coeff_goals_z (nullable) is None
        # and model_fields_set contains the field
        if self.off_coeff_goals_z is None and "off_coeff_goals_z" in self.model_fields_set:
            _dict['off_coeff_goals_z'] = None

        # set to None if def_coeff_context_xg_z (nullable) is None
        # and model_fields_set contains the field
        if self.def_coeff_context_xg_z is None and "def_coeff_context_xg_z" in self.model_fields_set:
            _dict['def_coeff_context_xg_z'] = None

        # set to None if def_coeff_corsi_z (nullable) is None
        # and model_fields_set contains the field
        if self.def_coeff_corsi_z is None and "def_coeff_corsi_z" in self.model_fields_set:
            _dict['def_coeff_corsi_z'] = None

        # set to None if def_coeff_goals_z (nullable) is None
        # and model_fields_set contains the field
        if self.def_coeff_goals_z is None and "def_coeff_goals_z" in self.model_fields_set:
            _dict['def_coeff_goals_z'] = None

        # set to None if metric_for_context_xg_z (nullable) is None
        # and model_fields_set contains the field
        if self.metric_for_context_xg_z is None and "metric_for_context_xg_z" in self.model_fields_set:
            _dict['metric_for_context_xg_z'] = None

        # set to None if metric_against_context_xg_z (nullable) is None
        # and model_fields_set contains the field
        if self.metric_against_context_xg_z is None and "metric_against_context_xg_z" in self.model_fields_set:
            _dict['metric_against_context_xg_z'] = None

        # set to None if metric_diff_context_xg_z (nullable) is None
        # and model_fields_set contains the field
        if self.metric_diff_context_xg_z is None and "metric_diff_context_xg_z" in self.model_fields_set:
            _dict['metric_diff_context_xg_z'] = None

        # set to None if metric_for_corsi_z (nullable) is None
        # and model_fields_set contains the field
        if self.metric_for_corsi_z is None and "metric_for_corsi_z" in self.model_fields_set:
            _dict['metric_for_corsi_z'] = None

        # set to None if metric_against_corsi_z (nullable) is None
        # and model_fields_set contains the field
        if self.metric_against_corsi_z is None and "metric_against_corsi_z" in self.model_fields_set:
            _dict['metric_against_corsi_z'] = None

        # set to None if metric_diff_corsi_z (nullable) is None
        # and model_fields_set contains the field
        if self.metric_diff_corsi_z is None and "metric_diff_corsi_z" in self.model_fields_set:
            _dict['metric_diff_corsi_z'] = None

        # set to None if metric_for_goals_z (nullable) is None
        # and model_fields_set contains the field
        if self.metric_for_goals_z is None and "metric_for_goals_z" in self.model_fields_set:
            _dict['metric_for_goals_z'] = None

        # set to None if metric_against_goals_z (nullable) is None
        # and model_fields_set contains the field
        if self.metric_against_goals_z is None and "metric_against_goals_z" in self.model_fields_set:
            _dict['metric_against_goals_z'] = None

        # set to None if metric_diff_goals_z (nullable) is None
        # and model_fields_set contains the field
        if self.metric_diff_goals_z is None and "metric_diff_goals_z" in self.model_fields_set:
            _dict['metric_diff_goals_z'] = None

        # set to None if on_ice_for_60_context_xg_z (nullable) is None
        # and model_fields_set contains the field
        if self.on_ice_for_60_context_xg_z is None and "on_ice_for_60_context_xg_z" in self.model_fields_set:
            _dict['on_ice_for_60_context_xg_z'] = None

        # set to None if on_ice_against_60_context_xg_z (nullable) is None
        # and model_fields_set contains the field
        if self.on_ice_against_60_context_xg_z is None and "on_ice_against_60_context_xg_z" in self.model_fields_set:
            _dict['on_ice_against_60_context_xg_z'] = None

        # set to None if on_ice_diff_60_context_xg_z (nullable) is None
        # and model_fields_set contains the field
        if self.on_ice_diff_60_context_xg_z is None and "on_ice_diff_60_context_xg_z" in self.model_fields_set:
            _dict['on_ice_diff_60_context_xg_z'] = None

        # set to None if on_ice_for_60_corsi_z (nullable) is None
        # and model_fields_set contains the field
        if self.on_ice_for_60_corsi_z is None and "on_ice_for_60_corsi_z" in self.model_fields_set:
            _dict['on_ice_for_60_corsi_z'] = None

        # set to None if on_ice_against_60_corsi_z (nullable) is None
        # and model_fields_set contains the field
        if self.on_ice_against_60_corsi_z is None and "on_ice_against_60_corsi_z" in self.model_fields_set:
            _dict['on_ice_against_60_corsi_z'] = None

        # set to None if on_ice_diff_60_corsi_z (nullable) is None
        # and model_fields_set contains the field
        if self.on_ice_diff_60_corsi_z is None and "on_ice_diff_60_corsi_z" in self.model_fields_set:
            _dict['on_ice_diff_60_corsi_z'] = None

        # set to None if on_ice_for_60_goals_z (nullable) is None
        # and model_fields_set contains the field
        if self.on_ice_for_60_goals_z is None and "on_ice_for_60_goals_z" in self.model_fields_set:
            _dict['on_ice_for_60_goals_z'] = None

        # set to None if on_ice_against_60_goals_z (nullable) is None
        # and model_fields_set contains the field
        if self.on_ice_against_60_goals_z is None and "on_ice_against_60_goals_z" in self.model_fields_set:
            _dict['on_ice_against_60_goals_z'] = None

        # set to None if on_ice_diff_60_goals_z (nullable) is None
        # and model_fields_set contains the field
        if self.on_ice_diff_60_goals_z is None and "on_ice_diff_60_goals_z" in self.model_fields_set:
            _dict['on_ice_diff_60_goals_z'] = None

        # set to None if total_rapm_context_xg_z (nullable) is None
        # and model_fields_set contains the field
        if self.total_rapm_context_xg_z is None and "total_rapm_context_xg_z" in self.model_fields_set:
            _dict['total_rapm_context_xg_z'] = None

        # set to None if total_rapm_corsi_z (nullable) is None
        # and model_fields_set contains the field
        if self.total_rapm_corsi_z is None and "total_rapm_corsi_z" in self.model_fields_set:
            _dict['total_rapm_corsi_z'] = None

        # set to None if total_rapm_goals_z (nullable) is None
        # and model_fields_set contains the field
        if self.total_rapm_goals_z is None and "total_rapm_goals_z" in self.model_fields_set:
            _dict['total_rapm_goals_z'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RapmScores from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "api_id": obj.get("api_id"),
            "season": obj.get("season"),
            "session": obj.get("session"),
            "situation": obj.get("situation"),
            "team": obj.get("team"),
            "pos": obj.get("pos"),
            "pos2": obj.get("pos2"),
            "toi_minutes": obj.get("toi_minutes"),
            "rapm_off": obj.get("rapm_off"),
            "rapm_def": obj.get("rapm_def"),
            "off_coeff_corsi": obj.get("off_coeff_corsi"),
            "off_coeff_goals": obj.get("off_coeff_goals"),
            "def_coeff_corsi": obj.get("def_coeff_corsi"),
            "def_coeff_goals": obj.get("def_coeff_goals"),
            "metric_for_context_xg": obj.get("metric_for_context_xg"),
            "metric_against_context_xg": obj.get("metric_against_context_xg"),
            "metric_diff_context_xg": obj.get("metric_diff_context_xg"),
            "metric_for_corsi": obj.get("metric_for_corsi"),
            "metric_against_corsi": obj.get("metric_against_corsi"),
            "metric_diff_corsi": obj.get("metric_diff_corsi"),
            "metric_for_goals": obj.get("metric_for_goals"),
            "metric_against_goals": obj.get("metric_against_goals"),
            "metric_diff_goals": obj.get("metric_diff_goals"),
            "on_ice_for_60_context_xg": obj.get("on_ice_for_60_context_xg"),
            "on_ice_against_60_context_xg": obj.get("on_ice_against_60_context_xg"),
            "on_ice_diff_60_context_xg": obj.get("on_ice_diff_60_context_xg"),
            "on_ice_for_60_corsi": obj.get("on_ice_for_60_corsi"),
            "on_ice_against_60_corsi": obj.get("on_ice_against_60_corsi"),
            "on_ice_diff_60_corsi": obj.get("on_ice_diff_60_corsi"),
            "on_ice_for_60_goals": obj.get("on_ice_for_60_goals"),
            "on_ice_against_60_goals": obj.get("on_ice_against_60_goals"),
            "on_ice_diff_60_goals": obj.get("on_ice_diff_60_goals"),
            "total_rapm_context_xg": obj.get("total_rapm_context_xg"),
            "total_rapm_corsi": obj.get("total_rapm_corsi"),
            "total_rapm_goals": obj.get("total_rapm_goals"),
            "off_coeff_context_xg_z": obj.get("off_coeff_context_xg_z"),
            "off_coeff_corsi_z": obj.get("off_coeff_corsi_z"),
            "off_coeff_goals_z": obj.get("off_coeff_goals_z"),
            "def_coeff_context_xg_z": obj.get("def_coeff_context_xg_z"),
            "def_coeff_corsi_z": obj.get("def_coeff_corsi_z"),
            "def_coeff_goals_z": obj.get("def_coeff_goals_z"),
            "metric_for_context_xg_z": obj.get("metric_for_context_xg_z"),
            "metric_against_context_xg_z": obj.get("metric_against_context_xg_z"),
            "metric_diff_context_xg_z": obj.get("metric_diff_context_xg_z"),
            "metric_for_corsi_z": obj.get("metric_for_corsi_z"),
            "metric_against_corsi_z": obj.get("metric_against_corsi_z"),
            "metric_diff_corsi_z": obj.get("metric_diff_corsi_z"),
            "metric_for_goals_z": obj.get("metric_for_goals_z"),
            "metric_against_goals_z": obj.get("metric_against_goals_z"),
            "metric_diff_goals_z": obj.get("metric_diff_goals_z"),
            "on_ice_for_60_context_xg_z": obj.get("on_ice_for_60_context_xg_z"),
            "on_ice_against_60_context_xg_z": obj.get("on_ice_against_60_context_xg_z"),
            "on_ice_diff_60_context_xg_z": obj.get("on_ice_diff_60_context_xg_z"),
            "on_ice_for_60_corsi_z": obj.get("on_ice_for_60_corsi_z"),
            "on_ice_against_60_corsi_z": obj.get("on_ice_against_60_corsi_z"),
            "on_ice_diff_60_corsi_z": obj.get("on_ice_diff_60_corsi_z"),
            "on_ice_for_60_goals_z": obj.get("on_ice_for_60_goals_z"),
            "on_ice_against_60_goals_z": obj.get("on_ice_against_60_goals_z"),
            "on_ice_diff_60_goals_z": obj.get("on_ice_diff_60_goals_z"),
            "total_rapm_context_xg_z": obj.get("total_rapm_context_xg_z"),
            "total_rapm_corsi_z": obj.get("total_rapm_corsi_z"),
            "total_rapm_goals_z": obj.get("total_rapm_goals_z")
        })
        return _obj


