# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.5
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from chickenstats_api.models.game_public import GamePublic
from chickenstats_api.models.player_public import PlayerPublic
from typing import Optional, Set
from typing_extensions import Self

class RosterPublic(BaseModel):
    """
    RosterPublic
    """ # noqa: E501
    game_id: StrictInt
    api_id: Optional[StrictInt] = None
    team: StrictStr
    jersey: Optional[StrictInt] = None
    position: Optional[StrictStr] = None
    starter: Optional[StrictInt] = None
    rookie: Optional[StrictInt] = None
    captain: Optional[StrictInt] = None
    alternate_captain: Optional[StrictInt] = None
    status: Optional[StrictStr] = None
    active: Optional[StrictInt] = None
    player: Optional[PlayerPublic] = None
    game: Optional[GamePublic] = None
    __properties: ClassVar[List[str]] = ["game_id", "api_id", "team", "jersey", "position", "starter", "rookie", "captain", "alternate_captain", "status", "active", "player", "game"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RosterPublic from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of player
        if self.player:
            _dict['player'] = self.player.to_dict()
        # override the default output from pydantic by calling `to_dict()` of game
        if self.game:
            _dict['game'] = self.game.to_dict()
        # set to None if api_id (nullable) is None
        # and model_fields_set contains the field
        if self.api_id is None and "api_id" in self.model_fields_set:
            _dict['api_id'] = None

        # set to None if jersey (nullable) is None
        # and model_fields_set contains the field
        if self.jersey is None and "jersey" in self.model_fields_set:
            _dict['jersey'] = None

        # set to None if position (nullable) is None
        # and model_fields_set contains the field
        if self.position is None and "position" in self.model_fields_set:
            _dict['position'] = None

        # set to None if starter (nullable) is None
        # and model_fields_set contains the field
        if self.starter is None and "starter" in self.model_fields_set:
            _dict['starter'] = None

        # set to None if rookie (nullable) is None
        # and model_fields_set contains the field
        if self.rookie is None and "rookie" in self.model_fields_set:
            _dict['rookie'] = None

        # set to None if captain (nullable) is None
        # and model_fields_set contains the field
        if self.captain is None and "captain" in self.model_fields_set:
            _dict['captain'] = None

        # set to None if alternate_captain (nullable) is None
        # and model_fields_set contains the field
        if self.alternate_captain is None and "alternate_captain" in self.model_fields_set:
            _dict['alternate_captain'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if active (nullable) is None
        # and model_fields_set contains the field
        if self.active is None and "active" in self.model_fields_set:
            _dict['active'] = None

        # set to None if player (nullable) is None
        # and model_fields_set contains the field
        if self.player is None and "player" in self.model_fields_set:
            _dict['player'] = None

        # set to None if game (nullable) is None
        # and model_fields_set contains the field
        if self.game is None and "game" in self.model_fields_set:
            _dict['game'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RosterPublic from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "game_id": obj.get("game_id"),
            "api_id": obj.get("api_id"),
            "team": obj.get("team"),
            "jersey": obj.get("jersey"),
            "position": obj.get("position"),
            "starter": obj.get("starter"),
            "rookie": obj.get("rookie"),
            "captain": obj.get("captain"),
            "alternate_captain": obj.get("alternate_captain"),
            "status": obj.get("status"),
            "active": obj.get("active"),
            "player": PlayerPublic.from_dict(obj["player"]) if obj.get("player") is not None else None,
            "game": GamePublic.from_dict(obj["game"]) if obj.get("game") is not None else None
        })
        return _obj


