# coding: utf-8

"""
    chickenstats API

    API for downloading NHL data

    The version of the OpenAPI document: 0.1.7
    Contact: chicken@chickenandstats.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from chickenstats_api.models.game_public import GamePublic
from chickenstats_api.models.player_public import PlayerPublic
from typing import Optional, Set
from typing_extensions import Self

class ShiftsPublic(BaseModel):
    """
    ShiftsPublic
    """ # noqa: E501
    season: StrictInt
    session: StrictStr
    game_id: StrictInt
    api_id: StrictInt
    team: StrictStr
    shift_count: StrictInt
    period: StrictInt
    start_time_seconds: StrictInt
    end_time_seconds: StrictInt
    duration_seconds: StrictInt
    goalie: Optional[StrictInt] = 0
    is_home: StrictInt
    is_away: StrictInt
    player: Optional[PlayerPublic] = None
    game: Optional[GamePublic] = None
    __properties: ClassVar[List[str]] = ["season", "session", "game_id", "api_id", "team", "shift_count", "period", "start_time_seconds", "end_time_seconds", "duration_seconds", "goalie", "is_home", "is_away", "player", "game"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ShiftsPublic from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of player
        if self.player:
            _dict['player'] = self.player.to_dict()
        # override the default output from pydantic by calling `to_dict()` of game
        if self.game:
            _dict['game'] = self.game.to_dict()
        # set to None if player (nullable) is None
        # and model_fields_set contains the field
        if self.player is None and "player" in self.model_fields_set:
            _dict['player'] = None

        # set to None if game (nullable) is None
        # and model_fields_set contains the field
        if self.game is None and "game" in self.model_fields_set:
            _dict['game'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ShiftsPublic from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "season": obj.get("season"),
            "session": obj.get("session"),
            "game_id": obj.get("game_id"),
            "api_id": obj.get("api_id"),
            "team": obj.get("team"),
            "shift_count": obj.get("shift_count"),
            "period": obj.get("period"),
            "start_time_seconds": obj.get("start_time_seconds"),
            "end_time_seconds": obj.get("end_time_seconds"),
            "duration_seconds": obj.get("duration_seconds"),
            "goalie": obj.get("goalie") if obj.get("goalie") is not None else 0,
            "is_home": obj.get("is_home"),
            "is_away": obj.get("is_away"),
            "player": PlayerPublic.from_dict(obj["player"]) if obj.get("player") is not None else None,
            "game": GamePublic.from_dict(obj["game"]) if obj.get("game") is not None else None
        })
        return _obj


